//! Bindings generated by `minwin` 0.1.0
#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types)]
::windows_targets::link!(
    "dwmapi.dll" "system" fn DwmEnableBlurBehindWindow(hWnd : HWND, pBlurBehind : * const
    DWM_BLURBEHIND) -> HRESULT
);
::windows_targets::link!(
    "gdi32.dll" "system" fn CreateRectRgn(x1 : i32, y1 : i32, x2 : i32, y2 : i32) -> HRGN
);
::windows_targets::link!("gdi32.dll" "system" fn DeleteObject(ho : HGDIOBJ) -> BOOL);
::windows_targets::link!(
    "gdi32.dll" "system" fn GetDeviceCaps(hdc : HDC, index : GET_DEVICE_CAPS_INDEX) ->
    i32
);
::windows_targets::link!(
    "imm32.dll" "system" fn ImmAssociateContextEx(param0 : HWND, param1 : HIMC, param2 :
    u32) -> BOOL
);
::windows_targets::link!(
    "imm32.dll" "system" fn ImmGetCompositionStringW(param0 : HIMC, param1 :
    IME_COMPOSITION_STRING, lpBuf : * mut ::core::ffi::c_void, dwBufLen : u32) -> i32
);
::windows_targets::link!("imm32.dll" "system" fn ImmGetContext(param0 : HWND) -> HIMC);
::windows_targets::link!(
    "imm32.dll" "system" fn ImmReleaseContext(param0 : HWND, param1 : HIMC) -> BOOL
);
::windows_targets::link!(
    "imm32.dll" "system" fn ImmSetCandidateWindow(param0 : HIMC, lpCandidate : * const
    CANDIDATEFORM) -> BOOL
);
::windows_targets::link!("kernel32.dll" "system" fn GetCurrentThreadId() -> u32);
::windows_targets::link!(
    "kernel32.dll" "system" fn GetProcAddress(hModule : HMODULE, lpProcName : PCSTR) ->
    FARPROC
);
::windows_targets::link!(
    "kernel32.dll" "system" fn LoadLibraryA(lpLibFileName : PCSTR) -> HMODULE
);
::windows_targets::link!(
    "ole32.dll" "system" fn CoCreateInstance(rclsid : * const GUID, pUnkOuter : IUnknown,
    dwClsContext : CLSCTX, riid : * const GUID, ppv : * mut * mut ::core::ffi::c_void) ->
    HRESULT
);
::windows_targets::link!(
    "ole32.dll" "system" fn CoInitializeEx(pvReserved : * const ::core::ffi::c_void,
    dwCoInit : COINIT) -> HRESULT
);
::windows_targets::link!("ole32.dll" "system" fn CoUninitialize() -> ());
::windows_targets::link!(
    "ole32.dll" "system" fn OleInitialize(pvReserved : * const ::core::ffi::c_void) ->
    HRESULT
);
::windows_targets::link!(
    "ole32.dll" "system" fn RegisterDragDrop(hwnd : HWND, pDropTarget : IDropTarget) ->
    HRESULT
);
::windows_targets::link!("ole32.dll" "system" fn RevokeDragDrop(hwnd : HWND) -> HRESULT);
::windows_targets::link!("shell32.dll" "system" fn DragFinish(hDrop : HDROP) -> ());
::windows_targets::link!(
    "shell32.dll" "system" fn DragQueryFileW(hDrop : HDROP, iFile : u32, lpszFile :
    PWSTR, cch : u32) -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn AdjustWindowRectEx(lpRect : * mut RECT, dwStyle :
    WINDOW_STYLE, bMenu : BOOL, dwExStyle : WINDOW_EX_STYLE) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn ChangeDisplaySettingsExW(lpszDeviceName : PCWSTR, lpDevMode
    : * const DEVMODEW, hwnd : HWND, dwflags : CDS_TYPE, lParam : * const
    ::core::ffi::c_void) -> DISP_CHANGE
);
::windows_targets::link!(
    "user32.dll" "system" fn ClientToScreen(hWnd : HWND, lpPoint : * mut POINT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn ClipCursor(lpRect : * const RECT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn CloseTouchInputHandle(hTouchInput : HTOUCHINPUT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn CreateIcon(hInstance : HMODULE, nWidth : i32, nHeight : i32,
    cPlanes : u8, cBitsPixel : u8, lpbANDbits : * const u8, lpbXORbits : * const u8) ->
    HICON
);
::windows_targets::link!(
    "user32.dll" "system" fn CreateWindowExW(dwExStyle : WINDOW_EX_STYLE, lpClassName :
    PCWSTR, lpWindowName : PCWSTR, dwStyle : WINDOW_STYLE, X : i32, Y : i32, nWidth :
    i32, nHeight : i32, hWndParent : HWND, hMenu : HMENU, hInstance : HMODULE, lpParam :
    * const ::core::ffi::c_void) -> HWND
);
::windows_targets::link!(
    "user32.dll" "system" fn DefWindowProcW(hWnd : HWND, Msg : u32, wParam : WPARAM,
    lParam : LPARAM) -> LRESULT
);
::windows_targets::link!("user32.dll" "system" fn DestroyIcon(hIcon : HICON) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn DestroyWindow(hWnd : HWND) -> BOOL);
::windows_targets::link!(
    "user32.dll" "system" fn DispatchMessageW(lpMsg : * const MSG) -> LRESULT
);
::windows_targets::link!(
    "user32.dll" "system" fn EnableMenuItem(hMenu : HMENU, uIDEnableItem : u32, uEnable :
    MENU_ITEM_FLAGS) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn EnableWindow(hWnd : HWND, bEnable : BOOL) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn EnumDisplayMonitors(hdc : HDC, lprcClip : * const RECT,
    lpfnEnum : MONITORENUMPROC, dwData : LPARAM) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn EnumDisplaySettingsExW(lpszDeviceName : PCWSTR, iModeNum :
    ENUM_DISPLAY_SETTINGS_MODE, lpDevMode : * mut DEVMODEW, dwFlags :
    ENUM_DISPLAY_SETTINGS_FLAGS) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn FlashWindowEx(pfwi : * const FLASHWINFO) -> BOOL
);
::windows_targets::link!("user32.dll" "system" fn GetActiveWindow() -> HWND);
::windows_targets::link!(
    "user32.dll" "system" fn GetClientRect(hWnd : HWND, lpRect : * mut RECT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetClipCursor(lpRect : * mut RECT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetCursorPos(lpPoint : * mut POINT) -> BOOL
);
::windows_targets::link!("user32.dll" "system" fn GetDC(hWnd : HWND) -> HDC);
::windows_targets::link!("user32.dll" "system" fn GetForegroundWindow() -> HWND);
::windows_targets::link!("user32.dll" "system" fn GetKeyState(nVirtKey : i32) -> i16);
::windows_targets::link!(
    "user32.dll" "system" fn GetKeyboardLayout(idThread : u32) -> HKL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetKeyboardState(lpKeyState : * mut u8) -> BOOL
);
::windows_targets::link!("user32.dll" "system" fn GetMenu(hWnd : HWND) -> HMENU);
::windows_targets::link!(
    "user32.dll" "system" fn GetMessageW(lpMsg : * mut MSG, hWnd : HWND, wMsgFilterMin :
    u32, wMsgFilterMax : u32) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetMonitorInfoW(hMonitor : HMONITOR, lpmi : * mut
    MONITORINFO) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetRawInputData(hRawInput : HRAWINPUT, uiCommand :
    RAW_INPUT_DATA_COMMAND_FLAGS, pData : * mut ::core::ffi::c_void, pcbSize : * mut u32,
    cbSizeHeader : u32) -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn GetRawInputDeviceInfoW(hDevice : HANDLE, uiCommand :
    RAW_INPUT_DEVICE_INFO_COMMAND, pData : * mut ::core::ffi::c_void, pcbSize : * mut
    u32) -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn GetRawInputDeviceList(pRawInputDeviceList : * mut
    RAWINPUTDEVICELIST, puiNumDevices : * mut u32, cbSize : u32) -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn GetSystemMenu(hWnd : HWND, bRevert : BOOL) -> HMENU
);
::windows_targets::link!(
    "user32.dll" "system" fn GetSystemMetrics(nIndex : SYSTEM_METRICS_INDEX) -> i32
);
::windows_targets::link!(
    "user32.dll" "system" fn GetTouchInputInfo(hTouchInput : HTOUCHINPUT, cInputs : u32,
    pInputs : * mut TOUCHINPUT, cbSize : i32) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetUpdateRect(hWnd : HWND, lpRect : * mut RECT, bErase :
    BOOL) -> BOOL
);
#[cfg(any(target_arch = "x86_64", target_arch = "aarch64"))]
::windows_targets::link!(
    "user32.dll" "system" fn GetWindowLongPtrW(hWnd : HWND, nIndex :
    WINDOW_LONG_PTR_INDEX) -> isize
);
::windows_targets::link!(
    "user32.dll" "system" fn GetWindowLongW(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX)
    -> i32
);
::windows_targets::link!(
    "user32.dll" "system" fn GetWindowPlacement(hWnd : HWND, lpwndpl : * mut
    WINDOWPLACEMENT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetWindowRect(hWnd : HWND, lpRect : * mut RECT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn GetWindowTextLengthW(hWnd : HWND) -> i32
);
::windows_targets::link!(
    "user32.dll" "system" fn GetWindowTextW(hWnd : HWND, lpString : PWSTR, nMaxCount :
    i32) -> i32
);
::windows_targets::link!(
    "user32.dll" "system" fn InvalidateRgn(hWnd : HWND, hRgn : HRGN, bErase : BOOL) ->
    BOOL
);
::windows_targets::link!("user32.dll" "system" fn IsIconic(hWnd : HWND) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn IsProcessDPIAware() -> BOOL);
::windows_targets::link!("user32.dll" "system" fn IsWindowVisible(hWnd : HWND) -> BOOL);
::windows_targets::link!(
    "user32.dll" "system" fn LoadCursorW(hInstance : HMODULE, lpCursorName : PCWSTR) ->
    HCURSOR
);
::windows_targets::link!(
    "user32.dll" "system" fn LoadImageW(hInst : HMODULE, name : PCWSTR, type_ :
    GDI_IMAGE_TYPE, cx : i32, cy : i32, fuLoad : IMAGE_FLAGS) -> LOADIMAGE_HANDLE
);
::windows_targets::link!(
    "user32.dll" "system" fn MapVirtualKeyA(uCode : u32, uMapType : MAP_VIRTUAL_KEY_TYPE)
    -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn MapVirtualKeyW(uCode : u32, uMapType : MAP_VIRTUAL_KEY_TYPE)
    -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn MonitorFromPoint(pt : POINT, dwFlags : MONITOR_FROM_FLAGS)
    -> HMONITOR
);
::windows_targets::link!(
    "user32.dll" "system" fn MonitorFromRect(lprc : * const RECT, dwFlags :
    MONITOR_FROM_FLAGS) -> HMONITOR
);
::windows_targets::link!(
    "user32.dll" "system" fn MonitorFromWindow(hwnd : HWND, dwFlags : MONITOR_FROM_FLAGS)
    -> HMONITOR
);
::windows_targets::link!(
    "user32.dll" "system" fn MsgWaitForMultipleObjectsEx(nCount : u32, pHandles : * const
    HANDLE, dwMilliseconds : u32, dwWakeMask : QUEUE_STATUS_FLAGS, dwFlags :
    MSG_WAIT_FOR_MULTIPLE_OBJECTS_EX_FLAGS) -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn PeekMessageW(lpMsg : * mut MSG, hWnd : HWND, wMsgFilterMin :
    u32, wMsgFilterMax : u32, wRemoveMsg : PEEK_MESSAGE_REMOVE_TYPE) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn PostMessageW(hWnd : HWND, Msg : u32, wParam : WPARAM, lParam
    : LPARAM) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn PostThreadMessageW(idThread : u32, Msg : u32, wParam :
    WPARAM, lParam : LPARAM) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn RedrawWindow(hWnd : HWND, lprcUpdate : * const RECT,
    hrgnUpdate : HRGN, flags : REDRAW_WINDOW_FLAGS) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn RegisterClassExW(param0 : * const WNDCLASSEXW) -> u16
);
::windows_targets::link!(
    "user32.dll" "system" fn RegisterRawInputDevices(pRawInputDevices : * const
    RAWINPUTDEVICE, uiNumDevices : u32, cbSize : u32) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn RegisterTouchWindow(hwnd : HWND, ulFlags :
    REGISTER_TOUCH_WINDOW_FLAGS) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn RegisterWindowMessageA(lpString : PCSTR) -> u32
);
::windows_targets::link!("user32.dll" "system" fn ReleaseCapture() -> BOOL);
::windows_targets::link!(
    "user32.dll" "system" fn ScreenToClient(hWnd : HWND, lpPoint : * mut POINT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn SendInput(cInputs : u32, pInputs : * const INPUT, cbSize :
    i32) -> u32
);
::windows_targets::link!(
    "user32.dll" "system" fn SendMessageW(hWnd : HWND, Msg : u32, wParam : WPARAM, lParam
    : LPARAM) -> LRESULT
);
::windows_targets::link!("user32.dll" "system" fn SetCapture(hWnd : HWND) -> HWND);
::windows_targets::link!(
    "user32.dll" "system" fn SetCursor(hCursor : HCURSOR) -> HCURSOR
);
::windows_targets::link!(
    "user32.dll" "system" fn SetCursorPos(X : i32, Y : i32) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn SetForegroundWindow(hWnd : HWND) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn SetWindowDisplayAffinity(hWnd : HWND, dwAffinity :
    WINDOW_DISPLAY_AFFINITY) -> BOOL
);
#[cfg(any(target_arch = "x86_64", target_arch = "aarch64"))]
::windows_targets::link!(
    "user32.dll" "system" fn SetWindowLongPtrW(hWnd : HWND, nIndex :
    WINDOW_LONG_PTR_INDEX, dwNewLong : isize) -> isize
);
::windows_targets::link!(
    "user32.dll" "system" fn SetWindowLongW(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX,
    dwNewLong : i32) -> i32
);
::windows_targets::link!(
    "user32.dll" "system" fn SetWindowPlacement(hWnd : HWND, lpwndpl : * const
    WINDOWPLACEMENT) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn SetWindowPos(hWnd : HWND, hWndInsertAfter : HWND, X : i32, Y
    : i32, cx : i32, cy : i32, uFlags : SET_WINDOW_POS_FLAGS) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn SetWindowTextW(hWnd : HWND, lpString : PCWSTR) -> BOOL
);
::windows_targets::link!("user32.dll" "system" fn ShowCursor(bShow : BOOL) -> i32);
::windows_targets::link!(
    "user32.dll" "system" fn ShowWindow(hWnd : HWND, nCmdShow : SHOW_WINDOW_CMD) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn SystemParametersInfoA(uiAction :
    SYSTEM_PARAMETERS_INFO_ACTION, uiParam : u32, pvParam : * mut ::core::ffi::c_void,
    fWinIni : SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn ToUnicodeEx(wVirtKey : u32, wScanCode : u32, lpKeyState : *
    const u8, pwszBuff : PWSTR, cchBuff : i32, wFlags : u32, dwhkl : HKL) -> i32
);
::windows_targets::link!(
    "user32.dll" "system" fn TrackMouseEvent(lpEventTrack : * mut TRACKMOUSEEVENT) ->
    BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn TranslateMessage(lpMsg : * const MSG) -> BOOL
);
::windows_targets::link!(
    "user32.dll" "system" fn ValidateRect(hWnd : HWND, lpRect : * const RECT) -> BOOL
);
::windows_targets::link!(
    "uxtheme.dll" "system" fn SetWindowTheme(hwnd : HWND, pszSubAppName : PCWSTR,
    pszSubIdList : PCWSTR) -> HRESULT
);
::windows_targets::link!("winmm.dll" "system" fn timeBeginPeriod(uPeriod : u32) -> u32);
::windows_targets::link!("winmm.dll" "system" fn timeEndPeriod(uPeriod : u32) -> u32);
::windows_targets::link!(
    "winmm.dll" "system" fn timeGetDevCaps(ptc : * mut TIMECAPS, cbtc : u32) -> u32
);
pub type CDS_TYPE = u32;
pub const CDS_FULLSCREEN: CDS_TYPE = 4;
pub type CLIPBOARD_FORMAT = u16;
pub const CF_HDROP: CLIPBOARD_FORMAT = 15;
pub type CLSCTX = u32;
pub const CLSCTX_ALL: CLSCTX = 23;
pub type COINIT = i32;
pub const COINIT_APARTMENTTHREADED: COINIT = 2;
pub type DEVMODE_COLLATE = u16;
pub type DEVMODE_COLOR = u16;
pub type DEVMODE_DISPLAY_FIXED_OUTPUT = u32;
pub type DEVMODE_DISPLAY_ORIENTATION = u32;
pub type DEVMODE_DUPLEX = u16;
pub type DEVMODE_FIELD_FLAGS = u32;
pub const DM_BITSPERPEL: DEVMODE_FIELD_FLAGS = 262144;
pub const DM_PELSWIDTH: DEVMODE_FIELD_FLAGS = 524288;
pub const DM_PELSHEIGHT: DEVMODE_FIELD_FLAGS = 1048576;
pub const DM_DISPLAYFREQUENCY: DEVMODE_FIELD_FLAGS = 4194304;
pub type DEVMODE_TRUETYPE_OPTION = u16;
pub type DISP_CHANGE = i32;
pub const DISP_CHANGE_BADPARAM: DISP_CHANGE = -5;
pub const DISP_CHANGE_BADFLAGS: DISP_CHANGE = -4;
pub const DISP_CHANGE_BADMODE: DISP_CHANGE = -2;
pub const DISP_CHANGE_FAILED: DISP_CHANGE = -1;
pub const DISP_CHANGE_SUCCESSFUL: DISP_CHANGE = 0;
pub type DPI_AWARENESS_CONTEXT = isize;
pub const DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE: DPI_AWARENESS_CONTEXT = -3;
pub type DROPEFFECT = u32;
pub const DROPEFFECT_NONE: DROPEFFECT = 0;
pub const DROPEFFECT_COPY: DROPEFFECT = 1;
pub type DVASPECT = u32;
pub const DVASPECT_CONTENT: DVASPECT = 1;
pub type ENUM_DISPLAY_SETTINGS_FLAGS = u32;
pub type ENUM_DISPLAY_SETTINGS_MODE = u32;
pub const ENUM_CURRENT_SETTINGS: ENUM_DISPLAY_SETTINGS_MODE = 4294967295;
pub type FLASHWINFO_FLAGS = u32;
pub const FLASHW_STOP: FLASHWINFO_FLAGS = 0;
pub const FLASHW_TRAY: FLASHWINFO_FLAGS = 2;
pub const FLASHW_ALL: FLASHWINFO_FLAGS = 3;
pub const FLASHW_TIMERNOFG: FLASHWINFO_FLAGS = 12;
pub type GDI_IMAGE_TYPE = u32;
pub const IMAGE_ICON: GDI_IMAGE_TYPE = 1;
pub type GET_DEVICE_CAPS_INDEX = u32;
pub const LOGPIXELSX: GET_DEVICE_CAPS_INDEX = 88;
pub type HIGHCONTRASTW_FLAGS = u32;
pub const HCF_HIGHCONTRASTON: HIGHCONTRASTW_FLAGS = 1;
pub const RPC_E_CHANGED_MODE: HRESULT = -2147417850 as _;
pub const OLE_E_WRONGCOMPOBJ: HRESULT = -2147221490 as _;
pub const DV_E_FORMATETC: HRESULT = -2147221404 as _;
pub const S_OK: HRESULT = 0 as _;
pub type HWND = isize;
pub const HWND_NOTOPMOST: HWND = -2;
pub const HWND_TOPMOST: HWND = -1;
pub const HWND_BOTTOM: HWND = 1;
pub type IMAGE_FLAGS = u32;
pub const LR_LOADFROMFILE: IMAGE_FLAGS = 16;
pub const LR_DEFAULTSIZE: IMAGE_FLAGS = 64;
pub type IME_COMPOSITION_STRING = u32;
pub const GCS_COMPSTR: IME_COMPOSITION_STRING = 8;
pub const GCS_COMPATTR: IME_COMPOSITION_STRING = 16;
pub const GCS_CURSORPOS: IME_COMPOSITION_STRING = 128;
pub const GCS_RESULTSTR: IME_COMPOSITION_STRING = 2048;
pub type INPUT_TYPE = u32;
pub const INPUT_KEYBOARD: INPUT_TYPE = 1;
pub type KEYBD_EVENT_FLAGS = u32;
pub const KEYEVENTF_EXTENDEDKEY: KEYBD_EVENT_FLAGS = 1;
pub const KEYEVENTF_KEYUP: KEYBD_EVENT_FLAGS = 2;
pub type MAP_VIRTUAL_KEY_TYPE = u32;
pub const MAPVK_VK_TO_VSC: MAP_VIRTUAL_KEY_TYPE = 0;
pub const MAPVK_VK_TO_CHAR: MAP_VIRTUAL_KEY_TYPE = 2;
pub const MAPVK_VSC_TO_VK_EX: MAP_VIRTUAL_KEY_TYPE = 3;
pub type MENU_ITEM_FLAGS = u32;
pub const MF_BYCOMMAND: MENU_ITEM_FLAGS = 0;
pub const MF_ENABLED: MENU_ITEM_FLAGS = 0;
pub const MF_DISABLED: MENU_ITEM_FLAGS = 2;
pub type MONITOR_DPI_TYPE = i32;
pub const MDT_EFFECTIVE_DPI: MONITOR_DPI_TYPE = 0;
pub type MONITOR_FROM_FLAGS = u32;
pub const MONITOR_DEFAULTTONULL: MONITOR_FROM_FLAGS = 0;
pub const MONITOR_DEFAULTTOPRIMARY: MONITOR_FROM_FLAGS = 1;
pub const MONITOR_DEFAULTTONEAREST: MONITOR_FROM_FLAGS = 2;
pub type MOUSE_EVENT_FLAGS = u32;
pub type MSG_WAIT_FOR_MULTIPLE_OBJECTS_EX_FLAGS = u32;
pub const MWMO_INPUTAVAILABLE: MSG_WAIT_FOR_MULTIPLE_OBJECTS_EX_FLAGS = 4;
pub const IDC_ARROW: PCWSTR = 32512 as _;
pub const IDC_IBEAM: PCWSTR = 32513 as _;
pub const IDC_WAIT: PCWSTR = 32514 as _;
pub const IDC_CROSS: PCWSTR = 32515 as _;
pub const IDC_SIZENWSE: PCWSTR = 32642 as _;
pub const IDC_SIZENESW: PCWSTR = 32643 as _;
pub const IDC_SIZEWE: PCWSTR = 32644 as _;
pub const IDC_SIZENS: PCWSTR = 32645 as _;
pub const IDC_SIZEALL: PCWSTR = 32646 as _;
pub const IDC_NO: PCWSTR = 32648 as _;
pub const IDC_HAND: PCWSTR = 32649 as _;
pub const IDC_APPSTARTING: PCWSTR = 32650 as _;
pub const IDC_HELP: PCWSTR = 32651 as _;
pub type PEEK_MESSAGE_REMOVE_TYPE = u32;
pub const PM_NOREMOVE: PEEK_MESSAGE_REMOVE_TYPE = 0;
pub const PM_REMOVE: PEEK_MESSAGE_REMOVE_TYPE = 1;
pub const PM_QS_PAINT: PEEK_MESSAGE_REMOVE_TYPE = 2097152;
pub type POINTER_BUTTON_CHANGE_TYPE = i32;
pub type POINTER_FLAGS = u32;
pub const POINTER_FLAG_DOWN: POINTER_FLAGS = 65536;
pub const POINTER_FLAG_UPDATE: POINTER_FLAGS = 131072;
pub const POINTER_FLAG_UP: POINTER_FLAGS = 262144;
pub type POINTER_INPUT_TYPE = i32;
pub const PT_TOUCH: POINTER_INPUT_TYPE = 2;
pub const PT_PEN: POINTER_INPUT_TYPE = 3;
pub type PROCESS_DPI_AWARENESS = i32;
pub const PROCESS_PER_MONITOR_DPI_AWARE: PROCESS_DPI_AWARENESS = 2;
pub type QUEUE_STATUS_FLAGS = u32;
pub const QS_ALLEVENTS: QUEUE_STATUS_FLAGS = 1215;
pub type RAWINPUTDEVICE_FLAGS = u32;
pub const RIDEV_REMOVE: RAWINPUTDEVICE_FLAGS = 1;
pub const RIDEV_INPUTSINK: RAWINPUTDEVICE_FLAGS = 256;
pub const RIDEV_DEVNOTIFY: RAWINPUTDEVICE_FLAGS = 8192;
pub type RAW_INPUT_DATA_COMMAND_FLAGS = u32;
pub const RID_INPUT: RAW_INPUT_DATA_COMMAND_FLAGS = 268435459;
pub type RAW_INPUT_DEVICE_INFO_COMMAND = u32;
pub const RIDI_DEVICENAME: RAW_INPUT_DEVICE_INFO_COMMAND = 536870919;
pub const RIDI_DEVICEINFO: RAW_INPUT_DEVICE_INFO_COMMAND = 536870923;
pub type REDRAW_WINDOW_FLAGS = u32;
pub const RDW_INTERNALPAINT: REDRAW_WINDOW_FLAGS = 2;
pub type REGISTER_TOUCH_WINDOW_FLAGS = u32;
pub const TWF_WANTPALM: REGISTER_TOUCH_WINDOW_FLAGS = 2;
pub type RID_DEVICE_INFO_TYPE = u32;
pub const RIM_TYPEMOUSE: RID_DEVICE_INFO_TYPE = 0;
pub const RIM_TYPEKEYBOARD: RID_DEVICE_INFO_TYPE = 1;
pub const RIM_TYPEHID: RID_DEVICE_INFO_TYPE = 2;
pub type SET_WINDOW_POS_FLAGS = u32;
pub const SWP_NOSIZE: SET_WINDOW_POS_FLAGS = 1;
pub const SWP_NOMOVE: SET_WINDOW_POS_FLAGS = 2;
pub const SWP_NOZORDER: SET_WINDOW_POS_FLAGS = 4;
pub const SWP_NOACTIVATE: SET_WINDOW_POS_FLAGS = 16;
pub const SWP_FRAMECHANGED: SET_WINDOW_POS_FLAGS = 32;
pub const SWP_NOREPOSITION: SET_WINDOW_POS_FLAGS = 512;
pub const SWP_ASYNCWINDOWPOS: SET_WINDOW_POS_FLAGS = 16384;
pub type SHOW_WINDOW_CMD = u32;
pub const SW_HIDE: SHOW_WINDOW_CMD = 0;
pub const SW_MAXIMIZE: SHOW_WINDOW_CMD = 3;
pub const SW_SHOWNOACTIVATE: SHOW_WINDOW_CMD = 4;
pub const SW_SHOW: SHOW_WINDOW_CMD = 5;
pub const SW_MINIMIZE: SHOW_WINDOW_CMD = 6;
pub const SW_RESTORE: SHOW_WINDOW_CMD = 9;
pub type SYSTEM_METRICS_INDEX = u32;
pub const SM_XVIRTUALSCREEN: SYSTEM_METRICS_INDEX = 76;
pub const SM_YVIRTUALSCREEN: SYSTEM_METRICS_INDEX = 77;
pub const SM_CXVIRTUALSCREEN: SYSTEM_METRICS_INDEX = 78;
pub const SM_CYVIRTUALSCREEN: SYSTEM_METRICS_INDEX = 79;
pub const SM_IMMENABLED: SYSTEM_METRICS_INDEX = 82;
pub const SM_DIGITIZER: SYSTEM_METRICS_INDEX = 94;
pub type SYSTEM_PARAMETERS_INFO_ACTION = u32;
pub const SPI_GETHIGHCONTRAST: SYSTEM_PARAMETERS_INFO_ACTION = 66;
pub type SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS = u32;
pub type TOUCHEVENTF_FLAGS = u32;
pub const TOUCHEVENTF_MOVE: TOUCHEVENTF_FLAGS = 1;
pub const TOUCHEVENTF_DOWN: TOUCHEVENTF_FLAGS = 2;
pub const TOUCHEVENTF_UP: TOUCHEVENTF_FLAGS = 4;
pub type TOUCHINPUTMASKF_MASK = u32;
pub type TRACKMOUSEEVENT_FLAGS = u32;
pub const TME_LEAVE: TRACKMOUSEEVENT_FLAGS = 2;
pub type TYMED = i32;
pub const TYMED_HGLOBAL: TYMED = 1;
pub type VIRTUAL_KEY = u16;
pub const VK_BACK: VIRTUAL_KEY = 8;
pub const VK_TAB: VIRTUAL_KEY = 9;
pub const VK_RETURN: VIRTUAL_KEY = 13;
pub const VK_SHIFT: VIRTUAL_KEY = 16;
pub const VK_CONTROL: VIRTUAL_KEY = 17;
pub const VK_MENU: VIRTUAL_KEY = 18;
pub const VK_PAUSE: VIRTUAL_KEY = 19;
pub const VK_CAPITAL: VIRTUAL_KEY = 20;
pub const VK_KANA: VIRTUAL_KEY = 21;
pub const VK_KANJI: VIRTUAL_KEY = 25;
pub const VK_ESCAPE: VIRTUAL_KEY = 27;
pub const VK_CONVERT: VIRTUAL_KEY = 28;
pub const VK_NONCONVERT: VIRTUAL_KEY = 29;
pub const VK_SPACE: VIRTUAL_KEY = 32;
pub const VK_PRIOR: VIRTUAL_KEY = 33;
pub const VK_NEXT: VIRTUAL_KEY = 34;
pub const VK_END: VIRTUAL_KEY = 35;
pub const VK_HOME: VIRTUAL_KEY = 36;
pub const VK_LEFT: VIRTUAL_KEY = 37;
pub const VK_UP: VIRTUAL_KEY = 38;
pub const VK_RIGHT: VIRTUAL_KEY = 39;
pub const VK_DOWN: VIRTUAL_KEY = 40;
pub const VK_SNAPSHOT: VIRTUAL_KEY = 44;
pub const VK_INSERT: VIRTUAL_KEY = 45;
pub const VK_DELETE: VIRTUAL_KEY = 46;
pub const VK_0: VIRTUAL_KEY = 48;
pub const VK_1: VIRTUAL_KEY = 49;
pub const VK_2: VIRTUAL_KEY = 50;
pub const VK_3: VIRTUAL_KEY = 51;
pub const VK_4: VIRTUAL_KEY = 52;
pub const VK_5: VIRTUAL_KEY = 53;
pub const VK_6: VIRTUAL_KEY = 54;
pub const VK_7: VIRTUAL_KEY = 55;
pub const VK_8: VIRTUAL_KEY = 56;
pub const VK_9: VIRTUAL_KEY = 57;
pub const VK_A: VIRTUAL_KEY = 65;
pub const VK_B: VIRTUAL_KEY = 66;
pub const VK_C: VIRTUAL_KEY = 67;
pub const VK_D: VIRTUAL_KEY = 68;
pub const VK_E: VIRTUAL_KEY = 69;
pub const VK_F: VIRTUAL_KEY = 70;
pub const VK_G: VIRTUAL_KEY = 71;
pub const VK_H: VIRTUAL_KEY = 72;
pub const VK_I: VIRTUAL_KEY = 73;
pub const VK_J: VIRTUAL_KEY = 74;
pub const VK_K: VIRTUAL_KEY = 75;
pub const VK_L: VIRTUAL_KEY = 76;
pub const VK_M: VIRTUAL_KEY = 77;
pub const VK_N: VIRTUAL_KEY = 78;
pub const VK_O: VIRTUAL_KEY = 79;
pub const VK_P: VIRTUAL_KEY = 80;
pub const VK_Q: VIRTUAL_KEY = 81;
pub const VK_R: VIRTUAL_KEY = 82;
pub const VK_S: VIRTUAL_KEY = 83;
pub const VK_T: VIRTUAL_KEY = 84;
pub const VK_U: VIRTUAL_KEY = 85;
pub const VK_V: VIRTUAL_KEY = 86;
pub const VK_W: VIRTUAL_KEY = 87;
pub const VK_X: VIRTUAL_KEY = 88;
pub const VK_Y: VIRTUAL_KEY = 89;
pub const VK_Z: VIRTUAL_KEY = 90;
pub const VK_LWIN: VIRTUAL_KEY = 91;
pub const VK_RWIN: VIRTUAL_KEY = 92;
pub const VK_APPS: VIRTUAL_KEY = 93;
pub const VK_SLEEP: VIRTUAL_KEY = 95;
pub const VK_NUMPAD0: VIRTUAL_KEY = 96;
pub const VK_NUMPAD1: VIRTUAL_KEY = 97;
pub const VK_NUMPAD2: VIRTUAL_KEY = 98;
pub const VK_NUMPAD3: VIRTUAL_KEY = 99;
pub const VK_NUMPAD4: VIRTUAL_KEY = 100;
pub const VK_NUMPAD5: VIRTUAL_KEY = 101;
pub const VK_NUMPAD6: VIRTUAL_KEY = 102;
pub const VK_NUMPAD7: VIRTUAL_KEY = 103;
pub const VK_NUMPAD8: VIRTUAL_KEY = 104;
pub const VK_NUMPAD9: VIRTUAL_KEY = 105;
pub const VK_MULTIPLY: VIRTUAL_KEY = 106;
pub const VK_ADD: VIRTUAL_KEY = 107;
pub const VK_SUBTRACT: VIRTUAL_KEY = 109;
pub const VK_DECIMAL: VIRTUAL_KEY = 110;
pub const VK_DIVIDE: VIRTUAL_KEY = 111;
pub const VK_F1: VIRTUAL_KEY = 112;
pub const VK_F2: VIRTUAL_KEY = 113;
pub const VK_F3: VIRTUAL_KEY = 114;
pub const VK_F4: VIRTUAL_KEY = 115;
pub const VK_F5: VIRTUAL_KEY = 116;
pub const VK_F6: VIRTUAL_KEY = 117;
pub const VK_F7: VIRTUAL_KEY = 118;
pub const VK_F8: VIRTUAL_KEY = 119;
pub const VK_F9: VIRTUAL_KEY = 120;
pub const VK_F10: VIRTUAL_KEY = 121;
pub const VK_F11: VIRTUAL_KEY = 122;
pub const VK_F12: VIRTUAL_KEY = 123;
pub const VK_F13: VIRTUAL_KEY = 124;
pub const VK_F14: VIRTUAL_KEY = 125;
pub const VK_F15: VIRTUAL_KEY = 126;
pub const VK_F16: VIRTUAL_KEY = 127;
pub const VK_F17: VIRTUAL_KEY = 128;
pub const VK_F18: VIRTUAL_KEY = 129;
pub const VK_F19: VIRTUAL_KEY = 130;
pub const VK_F20: VIRTUAL_KEY = 131;
pub const VK_F21: VIRTUAL_KEY = 132;
pub const VK_F22: VIRTUAL_KEY = 133;
pub const VK_F23: VIRTUAL_KEY = 134;
pub const VK_F24: VIRTUAL_KEY = 135;
pub const VK_NUMLOCK: VIRTUAL_KEY = 144;
pub const VK_SCROLL: VIRTUAL_KEY = 145;
pub const VK_LSHIFT: VIRTUAL_KEY = 160;
pub const VK_RSHIFT: VIRTUAL_KEY = 161;
pub const VK_LCONTROL: VIRTUAL_KEY = 162;
pub const VK_RCONTROL: VIRTUAL_KEY = 163;
pub const VK_LMENU: VIRTUAL_KEY = 164;
pub const VK_RMENU: VIRTUAL_KEY = 165;
pub const VK_BROWSER_BACK: VIRTUAL_KEY = 166;
pub const VK_BROWSER_FORWARD: VIRTUAL_KEY = 167;
pub const VK_BROWSER_REFRESH: VIRTUAL_KEY = 168;
pub const VK_BROWSER_STOP: VIRTUAL_KEY = 169;
pub const VK_BROWSER_SEARCH: VIRTUAL_KEY = 170;
pub const VK_BROWSER_FAVORITES: VIRTUAL_KEY = 171;
pub const VK_BROWSER_HOME: VIRTUAL_KEY = 172;
pub const VK_VOLUME_MUTE: VIRTUAL_KEY = 173;
pub const VK_VOLUME_DOWN: VIRTUAL_KEY = 174;
pub const VK_VOLUME_UP: VIRTUAL_KEY = 175;
pub const VK_MEDIA_NEXT_TRACK: VIRTUAL_KEY = 176;
pub const VK_MEDIA_PREV_TRACK: VIRTUAL_KEY = 177;
pub const VK_MEDIA_STOP: VIRTUAL_KEY = 178;
pub const VK_MEDIA_PLAY_PAUSE: VIRTUAL_KEY = 179;
pub const VK_LAUNCH_MAIL: VIRTUAL_KEY = 180;
pub const VK_LAUNCH_MEDIA_SELECT: VIRTUAL_KEY = 181;
pub const VK_OEM_1: VIRTUAL_KEY = 186;
pub const VK_OEM_PLUS: VIRTUAL_KEY = 187;
pub const VK_OEM_COMMA: VIRTUAL_KEY = 188;
pub const VK_OEM_MINUS: VIRTUAL_KEY = 189;
pub const VK_OEM_PERIOD: VIRTUAL_KEY = 190;
pub const VK_OEM_2: VIRTUAL_KEY = 191;
pub const VK_OEM_3: VIRTUAL_KEY = 192;
pub const VK_OEM_4: VIRTUAL_KEY = 219;
pub const VK_OEM_5: VIRTUAL_KEY = 220;
pub const VK_OEM_6: VIRTUAL_KEY = 221;
pub const VK_OEM_7: VIRTUAL_KEY = 222;
pub const VK_OEM_102: VIRTUAL_KEY = 226;
pub type WIN32_ERROR = u32;
pub const WAIT_TIMEOUT: WIN32_ERROR = 258;
pub type WINDOWPLACEMENT_FLAGS = u32;
pub type WINDOW_DISPLAY_AFFINITY = u32;
pub const WDA_NONE: WINDOW_DISPLAY_AFFINITY = 0;
pub const WDA_EXCLUDEFROMCAPTURE: WINDOW_DISPLAY_AFFINITY = 17;
pub type WINDOW_EX_STYLE = u32;
pub const WS_EX_TOPMOST: WINDOW_EX_STYLE = 8;
pub const WS_EX_ACCEPTFILES: WINDOW_EX_STYLE = 16;
pub const WS_EX_TRANSPARENT: WINDOW_EX_STYLE = 32;
pub const WS_EX_TOOLWINDOW: WINDOW_EX_STYLE = 128;
pub const WS_EX_WINDOWEDGE: WINDOW_EX_STYLE = 256;
pub const WS_EX_APPWINDOW: WINDOW_EX_STYLE = 262144;
pub const WS_EX_LAYERED: WINDOW_EX_STYLE = 524288;
pub const WS_EX_NOREDIRECTIONBITMAP: WINDOW_EX_STYLE = 2097152;
pub const WS_EX_NOACTIVATE: WINDOW_EX_STYLE = 134217728;
pub type WINDOW_LONG_PTR_INDEX = i32;
pub const GWL_USERDATA: WINDOW_LONG_PTR_INDEX = -21;
pub const GWL_EXSTYLE: WINDOW_LONG_PTR_INDEX = -20;
pub const GWL_STYLE: WINDOW_LONG_PTR_INDEX = -16;
pub const GWLP_HINSTANCE: WINDOW_LONG_PTR_INDEX = -6;
pub type WINDOW_STYLE = u32;
pub const WS_OVERLAPPED: WINDOW_STYLE = 0;
pub const WS_MAXIMIZEBOX: WINDOW_STYLE = 65536;
pub const WS_MINIMIZEBOX: WINDOW_STYLE = 131072;
pub const WS_SIZEBOX: WINDOW_STYLE = 262144;
pub const WS_SYSMENU: WINDOW_STYLE = 524288;
pub const WS_BORDER: WINDOW_STYLE = 8388608;
pub const WS_CAPTION: WINDOW_STYLE = 12582912;
pub const WS_OVERLAPPEDWINDOW: WINDOW_STYLE = 13565952;
pub const WS_MAXIMIZE: WINDOW_STYLE = 16777216;
pub const WS_CLIPCHILDREN: WINDOW_STYLE = 33554432;
pub const WS_CLIPSIBLINGS: WINDOW_STYLE = 67108864;
pub const WS_VISIBLE: WINDOW_STYLE = 268435456;
pub const WS_MINIMIZE: WINDOW_STYLE = 536870912;
pub const WS_CHILD: WINDOW_STYLE = 1073741824;
pub const WS_POPUP: WINDOW_STYLE = 2147483648;
pub type WNDCLASS_STYLES = u32;
pub const CS_VREDRAW: WNDCLASS_STYLES = 1;
pub const CS_HREDRAW: WNDCLASS_STYLES = 2;
pub const ATTR_TARGET_CONVERTED: u32 = 1;
pub const ATTR_TARGET_NOTCONVERTED: u32 = 3;
pub const CFS_EXCLUDE: u32 = 128;
pub const CW_USEDEFAULT: i32 = -2147483648;
pub const DWM_BB_BLURREGION: u32 = 2;
pub const DWM_BB_ENABLE: u32 = 1;
pub const GIDC_ARRIVAL: u32 = 1;
pub const GIDC_REMOVAL: u32 = 2;
pub const HID_USAGE_GENERIC_KEYBOARD: u16 = 6;
pub const HID_USAGE_GENERIC_MOUSE: u16 = 2;
pub const HID_USAGE_PAGE_GENERIC: u16 = 1;
pub const HOVER_DEFAULT: u32 = 4294967295;
pub const HTCAPTION: u32 = 2;
pub const HTCLIENT: u32 = 1;
pub const IACE_CHILDREN: u32 = 1;
pub const IACE_DEFAULT: u32 = 16;
pub const ICON_BIG: u32 = 1;
pub const ICON_SMALL: u32 = 0;
pub const INFINITE: u32 = 4294967295;
pub const ISC_SHOWUICOMPOSITIONWINDOW: u32 = 2147483648;
pub const MNC_CLOSE: u32 = 1;
pub const MOUSE_MOVE_RELATIVE: u32 = 0;
pub const NID_READY: u32 = 128;
pub const RI_KEY_E0: u32 = 2;
pub const RI_KEY_E1: u32 = 4;
pub const RI_MOUSE_LEFT_BUTTON_DOWN: u32 = 1;
pub const RI_MOUSE_LEFT_BUTTON_UP: u32 = 2;
pub const RI_MOUSE_MIDDLE_BUTTON_DOWN: u32 = 16;
pub const RI_MOUSE_MIDDLE_BUTTON_UP: u32 = 32;
pub const RI_MOUSE_RIGHT_BUTTON_DOWN: u32 = 4;
pub const RI_MOUSE_RIGHT_BUTTON_UP: u32 = 8;
pub const RI_MOUSE_WHEEL: u32 = 1024;
pub const SC_CLOSE: u32 = 61536;
pub const SC_MINIMIZE: u32 = 61472;
pub const SC_RESTORE: u32 = 61728;
pub const SC_SCREENSAVE: u32 = 61760;
pub const SIZE_MAXIMIZED: u32 = 2;
pub const TIMERR_NOERROR: u32 = 0;
pub const WHEEL_DELTA: u32 = 120;
pub const WM_CAPTURECHANGED: u32 = 533;
pub const WM_CHAR: u32 = 258;
pub const WM_CLOSE: u32 = 16;
pub const WM_CREATE: u32 = 1;
pub const WM_DESTROY: u32 = 2;
pub const WM_DPICHANGED: u32 = 736;
pub const WM_DROPFILES: u32 = 563;
pub const WM_ENTERSIZEMOVE: u32 = 561;
pub const WM_EXITSIZEMOVE: u32 = 562;
pub const WM_GETMINMAXINFO: u32 = 36;
pub const WM_IME_COMPOSITION: u32 = 271;
pub const WM_IME_ENDCOMPOSITION: u32 = 270;
pub const WM_IME_SETCONTEXT: u32 = 641;
pub const WM_IME_STARTCOMPOSITION: u32 = 269;
pub const WM_INPUT: u32 = 255;
pub const WM_INPUT_DEVICE_CHANGE: u32 = 254;
pub const WM_KEYDOWN: u32 = 256;
pub const WM_KEYUP: u32 = 257;
pub const WM_KILLFOCUS: u32 = 8;
pub const WM_LBUTTONDOWN: u32 = 513;
pub const WM_LBUTTONUP: u32 = 514;
pub const WM_MBUTTONDOWN: u32 = 519;
pub const WM_MBUTTONUP: u32 = 520;
pub const WM_MENUCHAR: u32 = 288;
pub const WM_MOUSEHWHEEL: u32 = 526;
pub const WM_MOUSELEAVE: u32 = 675;
pub const WM_MOUSEMOVE: u32 = 512;
pub const WM_MOUSEWHEEL: u32 = 522;
pub const WM_NCACTIVATE: u32 = 134;
pub const WM_NCCALCSIZE: u32 = 131;
pub const WM_NCCREATE: u32 = 129;
pub const WM_NCDESTROY: u32 = 130;
pub const WM_NCLBUTTONDOWN: u32 = 161;
pub const WM_PAINT: u32 = 15;
pub const WM_POINTERDOWN: u32 = 582;
pub const WM_POINTERUP: u32 = 583;
pub const WM_POINTERUPDATE: u32 = 581;
pub const WM_RBUTTONDOWN: u32 = 516;
pub const WM_RBUTTONUP: u32 = 517;
pub const WM_SETCURSOR: u32 = 32;
pub const WM_SETFOCUS: u32 = 7;
pub const WM_SETICON: u32 = 128;
pub const WM_SETTINGCHANGE: u32 = 26;
pub const WM_SIZE: u32 = 5;
pub const WM_SYSCHAR: u32 = 262;
pub const WM_SYSCOMMAND: u32 = 274;
pub const WM_SYSKEYDOWN: u32 = 260;
pub const WM_SYSKEYUP: u32 = 261;
pub const WM_TOUCH: u32 = 576;
pub const WM_WINDOWPOSCHANGED: u32 = 71;
pub const WM_WINDOWPOSCHANGING: u32 = 70;
pub const WM_XBUTTONDOWN: u32 = 523;
pub const WM_XBUTTONUP: u32 = 524;
pub type BOOL = i32;
#[repr(C)]
pub struct CANDIDATEFORM {
    pub dwIndex: u32,
    pub dwStyle: u32,
    pub ptCurrentPos: POINT,
    pub rcArea: RECT,
}
#[repr(C)]
pub struct CREATESTRUCTW {
    pub lpCreateParams: *mut ::core::ffi::c_void,
    pub hInstance: HMODULE,
    pub hMenu: HMENU,
    pub hwndParent: HWND,
    pub cy: i32,
    pub cx: i32,
    pub y: i32,
    pub x: i32,
    pub style: i32,
    pub lpszName: PCWSTR,
    pub lpszClass: PCWSTR,
    pub dwExStyle: u32,
}
#[repr(C)]
pub struct DEVMODEW {
    pub dmDeviceName: [u16; 32],
    pub dmSpecVersion: u16,
    pub dmDriverVersion: u16,
    pub dmSize: u16,
    pub dmDriverExtra: u16,
    pub dmFields: DEVMODE_FIELD_FLAGS,
    pub Anonymous1: DEVMODEW_0,
    pub dmColor: DEVMODE_COLOR,
    pub dmDuplex: DEVMODE_DUPLEX,
    pub dmYResolution: i16,
    pub dmTTOption: DEVMODE_TRUETYPE_OPTION,
    pub dmCollate: DEVMODE_COLLATE,
    pub dmFormName: [u16; 32],
    pub dmLogPixels: u16,
    pub dmBitsPerPel: u32,
    pub dmPelsWidth: u32,
    pub dmPelsHeight: u32,
    pub Anonymous2: DEVMODEW_1,
    pub dmDisplayFrequency: u32,
    pub dmICMMethod: u32,
    pub dmICMIntent: u32,
    pub dmMediaType: u32,
    pub dmDitherType: u32,
    pub dmReserved1: u32,
    pub dmReserved2: u32,
    pub dmPanningWidth: u32,
    pub dmPanningHeight: u32,
}
impl ::core::clone::Clone for DEVMODEW {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub union DEVMODEW_0 {
    pub Anonymous1: ::std::mem::ManuallyDrop<DEVMODEW_0_0>,
    pub Anonymous2: ::std::mem::ManuallyDrop<DEVMODEW_0_1>,
}
impl ::core::clone::Clone for DEVMODEW_0 {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct DEVMODEW_0_0 {
    pub dmOrientation: i16,
    pub dmPaperSize: i16,
    pub dmPaperLength: i16,
    pub dmPaperWidth: i16,
    pub dmScale: i16,
    pub dmCopies: i16,
    pub dmDefaultSource: i16,
    pub dmPrintQuality: i16,
}
impl ::core::clone::Clone for DEVMODEW_0_0 {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct DEVMODEW_0_1 {
    pub dmPosition: POINTL,
    pub dmDisplayOrientation: DEVMODE_DISPLAY_ORIENTATION,
    pub dmDisplayFixedOutput: DEVMODE_DISPLAY_FIXED_OUTPUT,
}
impl ::core::clone::Clone for DEVMODEW_0_1 {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub union DEVMODEW_1 {
    pub dmDisplayFlags: u32,
    pub dmNup: u32,
}
impl ::core::clone::Clone for DEVMODEW_1 {
    fn clone(&self) -> Self {
        *self
    }
}
pub type DPI_AWARENESS_CONTEXT = isize;
#[repr(C, packed(8))]
pub struct DVTARGETDEVICE {
    pub tdSize: u32,
    pub tdDriverNameOffset: u16,
    pub tdDeviceNameOffset: u16,
    pub tdPortNameOffset: u16,
    pub tdExtDevmodeOffset: u16,
    pub tdData: [u8; 1],
}
#[repr(C, packed(1))]
pub struct DWM_BLURBEHIND {
    pub dwFlags: u32,
    pub fEnable: BOOL,
    pub hRgnBlur: HRGN,
    pub fTransitionOnMaximized: BOOL,
}
pub type FARPROC = ::core::option::Option<unsafe extern "system" fn() -> isize>;
#[repr(C)]
pub struct FLASHWINFO {
    pub cbSize: u32,
    pub hwnd: HWND,
    pub dwFlags: FLASHWINFO_FLAGS,
    pub uCount: u32,
    pub dwTimeout: u32,
}
#[repr(C, packed(8))]
pub struct FORMATETC {
    pub cfFormat: u16,
    pub ptd: *mut DVTARGETDEVICE,
    pub dwAspect: u32,
    pub lindex: i32,
    pub tymed: u32,
}
#[repr(C)]
pub struct GUID {
    pub data1: u32,
    pub data2: u16,
    pub data3: u16,
    pub data4: [u8; 8],
}
impl ::core::marker::Copy for GUID {}
impl ::core::clone::Clone for GUID {
    fn clone(&self) -> Self {
        *self
    }
}
impl GUID {
    #[allow(dead_code)]
    pub const fn from_u128(uuid: u128) -> Self {
        Self {
            data1: (uuid >> 96) as u32,
            data2: (uuid >> 80 & 0xffff) as u16,
            data3: (uuid >> 64 & 0xffff) as u16,
            data4: (uuid as u64).to_be_bytes(),
        }
    }
}
pub type HANDLE = isize;
#[repr(C)]
pub struct HARDWAREINPUT {
    pub uMsg: u32,
    pub wParamL: u16,
    pub wParamH: u16,
}
pub type HBITMAP = isize;
pub type HBRUSH = isize;
pub type HCURSOR = isize;
pub type HDC = isize;
pub type HDROP = isize;
pub type HENHMETAFILE = isize;
pub type HGDIOBJ = isize;
pub type HGLOBAL = isize;
pub type HICON = isize;
#[repr(C)]
pub struct HIGHCONTRASTA {
    pub cbSize: u32,
    pub dwFlags: HIGHCONTRASTW_FLAGS,
    pub lpszDefaultScheme: PSTR,
}
pub type HIMC = isize;
pub type HKL = isize;
pub type HMENU = isize;
pub type HMODULE = isize;
pub type HMONITOR = isize;
pub type HRAWINPUT = isize;
pub type HRESULT = i32;
pub type HRGN = isize;
pub type HTOUCHINPUT = isize;
pub type HWND = isize;
pub type IDataObject = *mut ::core::ffi::c_void;
pub type IDropTarget = *mut ::core::ffi::c_void;
#[repr(C, packed(2))]
pub struct IMAGE_DOS_HEADER {
    pub e_magic: u16,
    pub e_cblp: u16,
    pub e_cp: u16,
    pub e_crlc: u16,
    pub e_cparhdr: u16,
    pub e_minalloc: u16,
    pub e_maxalloc: u16,
    pub e_ss: u16,
    pub e_sp: u16,
    pub e_csum: u16,
    pub e_ip: u16,
    pub e_cs: u16,
    pub e_lfarlc: u16,
    pub e_ovno: u16,
    pub e_res: [u16; 4],
    pub e_oemid: u16,
    pub e_oeminfo: u16,
    pub e_res2: [u16; 10],
    pub e_lfanew: i32,
}
#[repr(C)]
pub struct INPUT {
    pub type_: INPUT_TYPE,
    pub Anonymous: INPUT_0,
}
#[repr(C)]
pub union INPUT_0 {
    pub mi: ::std::mem::ManuallyDrop<MOUSEINPUT>,
    pub ki: ::std::mem::ManuallyDrop<KEYBDINPUT>,
    pub hi: ::std::mem::ManuallyDrop<HARDWAREINPUT>,
}
pub type IStorage = *mut ::core::ffi::c_void;
pub type IStream = *mut ::core::ffi::c_void;
pub type IUnknown = *mut ::core::ffi::c_void;
#[repr(C)]
pub struct KEYBDINPUT {
    pub wVk: VIRTUAL_KEY,
    pub wScan: u16,
    pub dwFlags: KEYBD_EVENT_FLAGS,
    pub time: u32,
    pub dwExtraInfo: usize,
}
pub type LOADIMAGE_HANDLE = isize;
pub type LPARAM = isize;
pub type LRESULT = isize;
#[repr(C)]
pub struct MINMAXINFO {
    pub ptReserved: POINT,
    pub ptMaxSize: POINT,
    pub ptMaxPosition: POINT,
    pub ptMinTrackSize: POINT,
    pub ptMaxTrackSize: POINT,
}
pub type MONITORENUMPROC = ::core::option::Option<
    unsafe extern "system" fn(
        param0: HMONITOR,
        param1: HDC,
        param2: *mut RECT,
        param3: LPARAM,
    ) -> BOOL,
>;
#[repr(C)]
pub struct MONITORINFO {
    pub cbSize: u32,
    pub rcMonitor: RECT,
    pub rcWork: RECT,
    pub dwFlags: u32,
}
#[repr(C)]
pub struct MONITORINFOEXW {
    pub monitorInfo: MONITORINFO,
    pub szDevice: [u16; 32],
}
#[repr(C)]
pub struct MOUSEINPUT {
    pub dx: i32,
    pub dy: i32,
    pub mouseData: i32,
    pub dwFlags: MOUSE_EVENT_FLAGS,
    pub time: u32,
    pub dwExtraInfo: usize,
}
#[repr(C)]
pub struct MSG {
    pub hwnd: HWND,
    pub message: u32,
    pub wParam: WPARAM,
    pub lParam: LPARAM,
    pub time: u32,
    pub pt: POINT,
}
#[repr(C)]
pub struct NCCALCSIZE_PARAMS {
    pub rgrc: [RECT; 3],
    pub lppos: *mut WINDOWPOS,
}
pub type NTSTATUS = i32;
#[repr(C)]
pub struct OSVERSIONINFOW {
    pub dwOSVersionInfoSize: u32,
    pub dwMajorVersion: u32,
    pub dwMinorVersion: u32,
    pub dwBuildNumber: u32,
    pub dwPlatformId: u32,
    pub szCSDVersion: [u16; 128],
}
pub type PCSTR = *const u8;
pub type PCWSTR = *const u16;
#[repr(C)]
pub struct POINT {
    pub x: i32,
    pub y: i32,
}
impl ::core::clone::Clone for POINT {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct POINTER_INFO {
    pub pointerType: POINTER_INPUT_TYPE,
    pub pointerId: u32,
    pub frameId: u32,
    pub pointerFlags: POINTER_FLAGS,
    pub sourceDevice: HANDLE,
    pub hwndTarget: HWND,
    pub ptPixelLocation: POINT,
    pub ptHimetricLocation: POINT,
    pub ptPixelLocationRaw: POINT,
    pub ptHimetricLocationRaw: POINT,
    pub dwTime: u32,
    pub historyCount: u32,
    pub InputData: i32,
    pub dwKeyStates: u32,
    pub PerformanceCount: u64,
    pub ButtonChangeType: POINTER_BUTTON_CHANGE_TYPE,
}
#[repr(C)]
pub struct POINTER_PEN_INFO {
    pub pointerInfo: POINTER_INFO,
    pub penFlags: u32,
    pub penMask: u32,
    pub pressure: u32,
    pub rotation: u32,
    pub tiltX: i32,
    pub tiltY: i32,
}
#[repr(C)]
pub struct POINTER_TOUCH_INFO {
    pub pointerInfo: POINTER_INFO,
    pub touchFlags: u32,
    pub touchMask: u32,
    pub rcContact: RECT,
    pub rcContactRaw: RECT,
    pub orientation: u32,
    pub pressure: u32,
}
#[repr(C)]
pub struct POINTL {
    pub x: i32,
    pub y: i32,
}
impl ::core::clone::Clone for POINTL {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct POINTS {
    pub x: i16,
    pub y: i16,
}
pub type PSTR = *mut u8;
pub type PWSTR = *mut u16;
#[repr(C)]
pub struct RAWHID {
    pub dwSizeHid: u32,
    pub dwCount: u32,
    pub bRawData: [u8; 1],
}
#[repr(C)]
pub struct RAWINPUT {
    pub header: RAWINPUTHEADER,
    pub data: RAWINPUT_0,
}
#[repr(C)]
pub union RAWINPUT_0 {
    pub mouse: ::std::mem::ManuallyDrop<RAWMOUSE>,
    pub keyboard: ::std::mem::ManuallyDrop<RAWKEYBOARD>,
    pub hid: ::std::mem::ManuallyDrop<RAWHID>,
}
#[repr(C)]
pub struct RAWINPUTDEVICE {
    pub usUsagePage: u16,
    pub usUsage: u16,
    pub dwFlags: RAWINPUTDEVICE_FLAGS,
    pub hwndTarget: HWND,
}
#[repr(C)]
pub struct RAWINPUTDEVICELIST {
    pub hDevice: HANDLE,
    pub dwType: RID_DEVICE_INFO_TYPE,
}
#[repr(C)]
pub struct RAWINPUTHEADER {
    pub dwType: u32,
    pub dwSize: u32,
    pub hDevice: HANDLE,
    pub wParam: WPARAM,
}
#[repr(C)]
pub struct RAWKEYBOARD {
    pub MakeCode: u16,
    pub Flags: u16,
    pub Reserved: u16,
    pub VKey: u16,
    pub Message: u32,
    pub ExtraInformation: u32,
}
#[repr(C)]
pub struct RAWMOUSE {
    pub usFlags: u16,
    pub Anonymous: RAWMOUSE_0,
    pub ulRawButtons: u32,
    pub lLastX: i32,
    pub lLastY: i32,
    pub ulExtraInformation: u32,
}
#[repr(C)]
pub union RAWMOUSE_0 {
    pub ulButtons: u32,
    pub Anonymous: ::std::mem::ManuallyDrop<RAWMOUSE_0_0>,
}
#[repr(C)]
pub struct RAWMOUSE_0_0 {
    pub usButtonFlags: u16,
    pub usButtonData: u16,
}
#[repr(C)]
pub struct RECT {
    pub left: i32,
    pub top: i32,
    pub right: i32,
    pub bottom: i32,
}
impl ::core::clone::Clone for RECT {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct RID_DEVICE_INFO {
    pub cbSize: u32,
    pub dwType: RID_DEVICE_INFO_TYPE,
    pub Anonymous: RID_DEVICE_INFO_0,
}
#[repr(C)]
pub union RID_DEVICE_INFO_0 {
    pub mouse: ::std::mem::ManuallyDrop<RID_DEVICE_INFO_MOUSE>,
    pub keyboard: ::std::mem::ManuallyDrop<RID_DEVICE_INFO_KEYBOARD>,
    pub hid: ::std::mem::ManuallyDrop<RID_DEVICE_INFO_HID>,
}
#[repr(C)]
pub struct RID_DEVICE_INFO_HID {
    pub dwVendorId: u32,
    pub dwProductId: u32,
    pub dwVersionNumber: u32,
    pub usUsagePage: u16,
    pub usUsage: u16,
}
#[repr(C)]
pub struct RID_DEVICE_INFO_KEYBOARD {
    pub dwType: u32,
    pub dwSubType: u32,
    pub dwKeyboardMode: u32,
    pub dwNumberOfFunctionKeys: u32,
    pub dwNumberOfIndicators: u32,
    pub dwNumberOfKeysTotal: u32,
}
#[repr(C)]
pub struct RID_DEVICE_INFO_MOUSE {
    pub dwId: u32,
    pub dwNumberOfButtons: u32,
    pub dwSampleRate: u32,
    pub fHasHorizontalWheel: BOOL,
}
#[repr(C)]
pub struct STGMEDIUM {
    pub tymed: TYMED,
    pub u: STGMEDIUM_0,
    pub pUnkForRelease: IUnknown,
}
#[repr(C)]
pub union STGMEDIUM_0 {
    pub hBitmap: HBITMAP,
    pub hMetaFilePict: *mut ::core::ffi::c_void,
    pub hEnhMetaFile: HENHMETAFILE,
    pub hGlobal: HGLOBAL,
    pub lpszFileName: PWSTR,
    pub pstm: ::std::mem::ManuallyDrop<IStream>,
    pub pstg: ::std::mem::ManuallyDrop<IStorage>,
}
#[repr(C, packed(1))]
pub struct TIMECAPS {
    pub wPeriodMin: u32,
    pub wPeriodMax: u32,
}
#[repr(C)]
pub struct TOUCHINPUT {
    pub x: i32,
    pub y: i32,
    pub hSource: HANDLE,
    pub dwID: u32,
    pub dwFlags: TOUCHEVENTF_FLAGS,
    pub dwMask: TOUCHINPUTMASKF_MASK,
    pub dwTime: u32,
    pub dwExtraInfo: usize,
    pub cxContact: u32,
    pub cyContact: u32,
}
#[repr(C)]
pub struct TRACKMOUSEEVENT {
    pub cbSize: u32,
    pub dwFlags: TRACKMOUSEEVENT_FLAGS,
    pub hwndTrack: HWND,
    pub dwHoverTime: u32,
}
#[repr(C)]
pub struct WINDOWPLACEMENT {
    pub length: u32,
    pub flags: WINDOWPLACEMENT_FLAGS,
    pub showCmd: SHOW_WINDOW_CMD,
    pub ptMinPosition: POINT,
    pub ptMaxPosition: POINT,
    pub rcNormalPosition: RECT,
}
impl ::core::clone::Clone for WINDOWPLACEMENT {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct WINDOWPOS {
    pub hwnd: HWND,
    pub hwndInsertAfter: HWND,
    pub x: i32,
    pub y: i32,
    pub cx: i32,
    pub cy: i32,
    pub flags: SET_WINDOW_POS_FLAGS,
}
#[repr(C)]
pub struct WNDCLASSEXW {
    pub cbSize: u32,
    pub style: WNDCLASS_STYLES,
    pub lpfnWndProc: WNDPROC,
    pub cbClsExtra: i32,
    pub cbWndExtra: i32,
    pub hInstance: HMODULE,
    pub hIcon: HICON,
    pub hCursor: HCURSOR,
    pub hbrBackground: HBRUSH,
    pub lpszMenuName: PCWSTR,
    pub lpszClassName: PCWSTR,
    pub hIconSm: HICON,
}
pub type WNDPROC = ::core::option::Option<
    unsafe extern "system" fn(
        param0: HWND,
        param1: u32,
        param2: WPARAM,
        param3: LPARAM,
    ) -> LRESULT,
>;
pub type WPARAM = usize;
