// Bindings generated by `windows-bindgen` 0.49.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]
::windows_targets::link!("dwmapi.dll" "system" fn DwmEnableBlurBehindWindow(hwnd : HWND, pblurbehind : *const DWM_BLURBEHIND) -> HRESULT);
::windows_targets::link!("gdi32.dll" "system" fn CreateRectRgn(x1 : i32, y1 : i32, x2 : i32, y2 : i32) -> HRGN);
::windows_targets::link!("gdi32.dll" "system" fn DeleteObject(ho : HGDIOBJ) -> BOOL);
::windows_targets::link!("gdi32.dll" "system" fn GetDeviceCaps(hdc : HDC, index : GET_DEVICE_CAPS_INDEX) -> i32);
::windows_targets::link!("kernel32.dll" "system" fn GetProcAddress(hmodule : HMODULE, lpprocname : PCSTR) -> FARPROC);
::windows_targets::link!("kernel32.dll" "system" fn LoadLibraryA(lplibfilename : PCSTR) -> HMODULE);
::windows_targets::link!("ole32.dll" "system" fn CoCreateInstance(rclsid : *const GUID, punkouter : IUnknown, dwclscontext : CLSCTX, riid : *const GUID, ppv : *mut *mut ::core::ffi::c_void) -> HRESULT);
::windows_targets::link!("ole32.dll" "system" fn CoInitializeEx(pvreserved : *const ::core::ffi::c_void, dwcoinit : COINIT) -> HRESULT);
::windows_targets::link!("ole32.dll" "system" fn CoUninitialize() -> ());
::windows_targets::link!("ole32.dll" "system" fn OleInitialize(pvreserved : *const ::core::ffi::c_void) -> HRESULT);
::windows_targets::link!("ole32.dll" "system" fn RegisterDragDrop(hwnd : HWND, pdroptarget : IDropTarget) -> HRESULT);
::windows_targets::link!("ole32.dll" "system" fn RevokeDragDrop(hwnd : HWND) -> HRESULT);
::windows_targets::link!("shell32.dll" "system" fn DragFinish(hdrop : HDROP) -> ());
::windows_targets::link!("shell32.dll" "system" fn DragQueryFileW(hdrop : HDROP, ifile : u32, lpszfile : PWSTR, cch : u32) -> u32);
::windows_targets::link!("user32.dll" "system" fn ChangeDisplaySettingsExW(lpszdevicename : PCWSTR, lpdevmode : *const DEVMODEW, hwnd : HWND, dwflags : CDS_TYPE, lparam : *const ::core::ffi::c_void) -> DISP_CHANGE);
::windows_targets::link!("user32.dll" "system" fn ClientToScreen(hwnd : HWND, lppoint : *mut POINT) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn EnumDisplayMonitors(hdc : HDC, lprcclip : *const RECT, lpfnenum : MONITORENUMPROC, dwdata : LPARAM) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn EnumDisplaySettingsExW(lpszdevicename : PCWSTR, imodenum : ENUM_DISPLAY_SETTINGS_MODE, lpdevmode : *mut DEVMODEW, dwflags : ENUM_DISPLAY_SETTINGS_FLAGS) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn GetDC(hwnd : HWND) -> HDC);
::windows_targets::link!("user32.dll" "system" fn GetMonitorInfoW(hmonitor : HMONITOR, lpmi : *mut MONITORINFO) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn InvalidateRgn(hwnd : HWND, hrgn : HRGN, berase : BOOL) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn IsProcessDPIAware() -> BOOL);
::windows_targets::link!("user32.dll" "system" fn LoadImageW(hinst : HMODULE, name : PCWSTR, r#type : GDI_IMAGE_TYPE, cx : i32, cy : i32, fuload : IMAGE_FLAGS) -> LOADIMAGE_HANDLE);
::windows_targets::link!("user32.dll" "system" fn MonitorFromPoint(pt : POINT, dwflags : MONITOR_FROM_FLAGS) -> HMONITOR);
::windows_targets::link!("user32.dll" "system" fn MonitorFromRect(lprc : *const RECT, dwflags : MONITOR_FROM_FLAGS) -> HMONITOR);
::windows_targets::link!("user32.dll" "system" fn MonitorFromWindow(hwnd : HWND, dwflags : MONITOR_FROM_FLAGS) -> HMONITOR);
::windows_targets::link!("user32.dll" "system" fn RedrawWindow(hwnd : HWND, lprcupdate : *const RECT, hrgnupdate : HRGN, flags : REDRAW_WINDOW_FLAGS) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn ScreenToClient(hwnd : HWND, lppoint : *mut POINT) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn SystemParametersInfoA(uiaction : SYSTEM_PARAMETERS_INFO_ACTION, uiparam : u32, pvparam : *mut ::core::ffi::c_void, fwinini : SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS) -> BOOL);
::windows_targets::link!("user32.dll" "system" fn ValidateRect(hwnd : HWND, lprect : *const RECT) -> BOOL);
::windows_targets::link!("uxtheme.dll" "system" fn SetWindowTheme(hwnd : HWND, pszsubappname : PCWSTR, pszsubidlist : PCWSTR) -> HRESULT);
#[repr(C)]
pub struct BIND_OPTS {
    pub cbStruct: u32,
    pub grfFlags: u32,
    pub grfMode: u32,
    pub dwTickCountDeadline: u32,
}
impl ::core::marker::Copy for BIND_OPTS {}
impl ::core::clone::Clone for BIND_OPTS {
    fn clone(&self) -> Self {
        *self
    }
}
pub type BOOL = i32;
pub const CDS_FULLSCREEN: CDS_TYPE = 4u32;
pub type CDS_TYPE = u32;
pub const CF_HDROP: CLIPBOARD_FORMAT = 15u16;
pub type CLIPBOARD_FORMAT = u16;
pub type CLSCTX = u32;
pub const CLSCTX_ALL: CLSCTX = 23u32;
pub type COINIT = i32;
pub const COINIT_APARTMENTTHREADED: COINIT = 2i32;
#[repr(C)]
pub struct DEVMODEW {
    pub dmDeviceName: [u16; 32],
    pub dmSpecVersion: u16,
    pub dmDriverVersion: u16,
    pub dmSize: u16,
    pub dmDriverExtra: u16,
    pub dmFields: DEVMODE_FIELD_FLAGS,
    pub Anonymous1: DEVMODEW_0,
    pub dmColor: DEVMODE_COLOR,
    pub dmDuplex: DEVMODE_DUPLEX,
    pub dmYResolution: i16,
    pub dmTTOption: DEVMODE_TRUETYPE_OPTION,
    pub dmCollate: DEVMODE_COLLATE,
    pub dmFormName: [u16; 32],
    pub dmLogPixels: u16,
    pub dmBitsPerPel: u32,
    pub dmPelsWidth: u32,
    pub dmPelsHeight: u32,
    pub Anonymous2: DEVMODEW_1,
    pub dmDisplayFrequency: u32,
    pub dmICMMethod: u32,
    pub dmICMIntent: u32,
    pub dmMediaType: u32,
    pub dmDitherType: u32,
    pub dmReserved1: u32,
    pub dmReserved2: u32,
    pub dmPanningWidth: u32,
    pub dmPanningHeight: u32,
}
impl ::core::marker::Copy for DEVMODEW {}
impl ::core::clone::Clone for DEVMODEW {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub union DEVMODEW_0 {
    pub Anonymous1: DEVMODEW_0_0,
    pub Anonymous2: DEVMODEW_0_1,
}
impl ::core::marker::Copy for DEVMODEW_0 {}
impl ::core::clone::Clone for DEVMODEW_0 {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct DEVMODEW_0_0 {
    pub dmOrientation: i16,
    pub dmPaperSize: i16,
    pub dmPaperLength: i16,
    pub dmPaperWidth: i16,
    pub dmScale: i16,
    pub dmCopies: i16,
    pub dmDefaultSource: i16,
    pub dmPrintQuality: i16,
}
impl ::core::marker::Copy for DEVMODEW_0_0 {}
impl ::core::clone::Clone for DEVMODEW_0_0 {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct DEVMODEW_0_1 {
    pub dmPosition: POINTL,
    pub dmDisplayOrientation: DEVMODE_DISPLAY_ORIENTATION,
    pub dmDisplayFixedOutput: DEVMODE_DISPLAY_FIXED_OUTPUT,
}
impl ::core::marker::Copy for DEVMODEW_0_1 {}
impl ::core::clone::Clone for DEVMODEW_0_1 {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub union DEVMODEW_1 {
    pub dmDisplayFlags: u32,
    pub dmNup: u32,
}
impl ::core::marker::Copy for DEVMODEW_1 {}
impl ::core::clone::Clone for DEVMODEW_1 {
    fn clone(&self) -> Self {
        *self
    }
}
pub type DEVMODE_COLLATE = u16;
pub type DEVMODE_COLOR = u16;
pub type DEVMODE_DISPLAY_FIXED_OUTPUT = u32;
pub type DEVMODE_DISPLAY_ORIENTATION = u32;
pub type DEVMODE_DUPLEX = u16;
pub type DEVMODE_FIELD_FLAGS = u32;
pub type DEVMODE_TRUETYPE_OPTION = u16;
pub type DISP_CHANGE = i32;
pub const DISP_CHANGE_BADFLAGS: DISP_CHANGE = -4i32;
pub const DISP_CHANGE_BADMODE: DISP_CHANGE = -2i32;
pub const DISP_CHANGE_BADPARAM: DISP_CHANGE = -5i32;
pub const DISP_CHANGE_FAILED: DISP_CHANGE = -1i32;
pub const DISP_CHANGE_SUCCESSFUL: DISP_CHANGE = 0i32;
pub const DM_BITSPERPEL: DEVMODE_FIELD_FLAGS = 262144u32;
pub const DM_DISPLAYFREQUENCY: DEVMODE_FIELD_FLAGS = 4194304u32;
pub const DM_PELSHEIGHT: DEVMODE_FIELD_FLAGS = 1048576u32;
pub const DM_PELSWIDTH: DEVMODE_FIELD_FLAGS = 524288u32;
pub type DPI_AWARENESS_CONTEXT = isize;
pub const DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE: DPI_AWARENESS_CONTEXT = -3i32 as _;
pub type DROPEFFECT = u32;
pub const DROPEFFECT_COPY: DROPEFFECT = 1u32;
pub const DROPEFFECT_NONE: DROPEFFECT = 0u32;
pub type DVASPECT = u32;
pub const DVASPECT_CONTENT: DVASPECT = 1u32;
#[repr(C)]
pub struct DVTARGETDEVICE {
    pub tdSize: u32,
    pub tdDriverNameOffset: u16,
    pub tdDeviceNameOffset: u16,
    pub tdPortNameOffset: u16,
    pub tdExtDevmodeOffset: u16,
    pub tdData: [u8; 1],
}
impl ::core::marker::Copy for DVTARGETDEVICE {}
impl ::core::clone::Clone for DVTARGETDEVICE {
    fn clone(&self) -> Self {
        *self
    }
}
pub const DV_E_FORMATETC: HRESULT = -2147221404i32;
pub const DWM_BB_BLURREGION: u32 = 2u32;
pub const DWM_BB_ENABLE: u32 = 1u32;
#[repr(C, packed(1))]
pub struct DWM_BLURBEHIND {
    pub dwFlags: u32,
    pub fEnable: BOOL,
    pub hRgnBlur: HRGN,
    pub fTransitionOnMaximized: BOOL,
}
impl ::core::marker::Copy for DWM_BLURBEHIND {}
impl ::core::clone::Clone for DWM_BLURBEHIND {
    fn clone(&self) -> Self {
        *self
    }
}
pub const ENUM_CURRENT_SETTINGS: ENUM_DISPLAY_SETTINGS_MODE = 4294967295u32;
pub type ENUM_DISPLAY_SETTINGS_FLAGS = u32;
pub type ENUM_DISPLAY_SETTINGS_MODE = u32;
pub type FARPROC = ::core::option::Option<unsafe extern "system" fn() -> isize>;
#[repr(C)]
pub struct FILETIME {
    pub dwLowDateTime: u32,
    pub dwHighDateTime: u32,
}
impl ::core::marker::Copy for FILETIME {}
impl ::core::clone::Clone for FILETIME {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct FORMATETC {
    pub cfFormat: u16,
    pub ptd: *mut DVTARGETDEVICE,
    pub dwAspect: u32,
    pub lindex: i32,
    pub tymed: u32,
}
impl ::core::marker::Copy for FORMATETC {}
impl ::core::clone::Clone for FORMATETC {
    fn clone(&self) -> Self {
        *self
    }
}
pub type GDI_IMAGE_TYPE = u32;
pub type GET_DEVICE_CAPS_INDEX = u32;
#[repr(C)]
pub struct GUID {
    pub data1: u32,
    pub data2: u16,
    pub data3: u16,
    pub data4: [u8; 8],
}
impl ::core::marker::Copy for GUID {}
impl ::core::clone::Clone for GUID {
    fn clone(&self) -> Self {
        *self
    }
}
impl GUID {
    pub const fn from_u128(uuid: u128) -> Self {
        Self {
            data1: (uuid >> 96) as u32,
            data2: (uuid >> 80 & 0xffff) as u16,
            data3: (uuid >> 64 & 0xffff) as u16,
            data4: (uuid as u64).to_be_bytes(),
        }
    }
}
pub type HBITMAP = isize;
pub const HCF_HIGHCONTRASTON: HIGHCONTRASTW_FLAGS = 1u32;
pub type HDC = isize;
pub type HDROP = isize;
pub type HENHMETAFILE = isize;
pub type HGDIOBJ = isize;
pub type HGLOBAL = isize;
#[repr(C)]
pub struct HIGHCONTRASTA {
    pub cbSize: u32,
    pub dwFlags: HIGHCONTRASTW_FLAGS,
    pub lpszDefaultScheme: PSTR,
}
impl ::core::marker::Copy for HIGHCONTRASTA {}
impl ::core::clone::Clone for HIGHCONTRASTA {
    fn clone(&self) -> Self {
        *self
    }
}
pub type HIGHCONTRASTW_FLAGS = u32;
pub type HMODULE = isize;
pub type HMONITOR = isize;
pub type HRESULT = i32;
pub type HRGN = isize;
pub type HWND = isize;
pub type IAdviseSink = *mut ::core::ffi::c_void;
pub type IBindCtx = *mut ::core::ffi::c_void;
pub type IDataObject = *mut ::core::ffi::c_void;
pub type IDropTarget = *mut ::core::ffi::c_void;
pub type IEnumFORMATETC = *mut ::core::ffi::c_void;
pub type IEnumMoniker = *mut ::core::ffi::c_void;
pub type IEnumSTATDATA = *mut ::core::ffi::c_void;
pub type IEnumSTATSTG = *mut ::core::ffi::c_void;
pub type IEnumString = *mut ::core::ffi::c_void;
pub type IMAGE_FLAGS = u32;
pub type IMoniker = *mut ::core::ffi::c_void;
pub type IPersist = *mut ::core::ffi::c_void;
pub type IPersistStream = *mut ::core::ffi::c_void;
pub type IRunningObjectTable = *mut ::core::ffi::c_void;
pub type ISequentialStream = *mut ::core::ffi::c_void;
pub type IStorage = *mut ::core::ffi::c_void;
pub type IStream = *mut ::core::ffi::c_void;
pub type IUnknown = *mut ::core::ffi::c_void;
pub type LOADIMAGE_HANDLE = isize;
pub type LOCKTYPE = i32;
pub const LOGPIXELSX: GET_DEVICE_CAPS_INDEX = 88u32;
pub type LPARAM = isize;
pub const MDT_EFFECTIVE_DPI: MONITOR_DPI_TYPE = 0i32;
pub type MODIFIERKEYS_FLAGS = u32;
pub type MONITORENUMPROC = ::core::option::Option<
    unsafe extern "system" fn(
        param0: HMONITOR,
        param1: HDC,
        param2: *mut RECT,
        param3: LPARAM,
    ) -> BOOL,
>;
#[repr(C)]
pub struct MONITORINFO {
    pub cbSize: u32,
    pub rcMonitor: RECT,
    pub rcWork: RECT,
    pub dwFlags: u32,
}
impl ::core::marker::Copy for MONITORINFO {}
impl ::core::clone::Clone for MONITORINFO {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct MONITORINFOEXW {
    pub monitorInfo: MONITORINFO,
    pub szDevice: [u16; 32],
}
impl ::core::marker::Copy for MONITORINFOEXW {}
impl ::core::clone::Clone for MONITORINFOEXW {
    fn clone(&self) -> Self {
        *self
    }
}
pub const MONITOR_DEFAULTTONEAREST: MONITOR_FROM_FLAGS = 2u32;
pub const MONITOR_DEFAULTTONULL: MONITOR_FROM_FLAGS = 0u32;
pub const MONITOR_DEFAULTTOPRIMARY: MONITOR_FROM_FLAGS = 1u32;
pub type MONITOR_DPI_TYPE = i32;
pub type MONITOR_FROM_FLAGS = u32;
pub type NTSTATUS = i32;
pub const OLE_E_WRONGCOMPOBJ: HRESULT = -2147221490i32;
#[repr(C)]
pub struct OSVERSIONINFOW {
    pub dwOSVersionInfoSize: u32,
    pub dwMajorVersion: u32,
    pub dwMinorVersion: u32,
    pub dwBuildNumber: u32,
    pub dwPlatformId: u32,
    pub szCSDVersion: [u16; 128],
}
impl ::core::marker::Copy for OSVERSIONINFOW {}
impl ::core::clone::Clone for OSVERSIONINFOW {
    fn clone(&self) -> Self {
        *self
    }
}
pub type PCSTR = *const u8;
pub type PCWSTR = *const u16;
#[repr(C)]
pub struct POINT {
    pub x: i32,
    pub y: i32,
}
impl ::core::marker::Copy for POINT {}
impl ::core::clone::Clone for POINT {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct POINTL {
    pub x: i32,
    pub y: i32,
}
impl ::core::marker::Copy for POINTL {}
impl ::core::clone::Clone for POINTL {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub struct POINTS {
    pub x: i16,
    pub y: i16,
}
impl ::core::marker::Copy for POINTS {}
impl ::core::clone::Clone for POINTS {
    fn clone(&self) -> Self {
        *self
    }
}
pub type PROCESS_DPI_AWARENESS = i32;
pub const PROCESS_PER_MONITOR_DPI_AWARE: PROCESS_DPI_AWARENESS = 2i32;
pub type PSTR = *mut u8;
pub type PWSTR = *mut u16;
pub const RDW_INTERNALPAINT: REDRAW_WINDOW_FLAGS = 2u32;
#[repr(C)]
pub struct RECT {
    pub left: i32,
    pub top: i32,
    pub right: i32,
    pub bottom: i32,
}
impl ::core::marker::Copy for RECT {}
impl ::core::clone::Clone for RECT {
    fn clone(&self) -> Self {
        *self
    }
}
pub type REDRAW_WINDOW_FLAGS = u32;
pub type ROT_FLAGS = u32;
pub const RPC_E_CHANGED_MODE: HRESULT = -2147417850i32;
pub const SC_MINIMIZE: u32 = 61472u32;
pub const SC_RESTORE: u32 = 61728u32;
pub const SC_SCREENSAVE: u32 = 61760u32;
pub const SPI_GETHIGHCONTRAST: SYSTEM_PARAMETERS_INFO_ACTION = 66u32;
#[repr(C)]
pub struct STATDATA {
    pub formatetc: FORMATETC,
    pub advf: u32,
    pub pAdvSink: IAdviseSink,
    pub dwConnection: u32,
}
impl ::core::marker::Copy for STATDATA {}
impl ::core::clone::Clone for STATDATA {
    fn clone(&self) -> Self {
        *self
    }
}
pub type STATFLAG = i32;
#[repr(C)]
pub struct STATSTG {
    pub pwcsName: PWSTR,
    pub r#type: u32,
    pub cbSize: u64,
    pub mtime: FILETIME,
    pub ctime: FILETIME,
    pub atime: FILETIME,
    pub grfMode: STGM,
    pub grfLocksSupported: LOCKTYPE,
    pub clsid: GUID,
    pub grfStateBits: u32,
    pub reserved: u32,
}
impl ::core::marker::Copy for STATSTG {}
impl ::core::clone::Clone for STATSTG {
    fn clone(&self) -> Self {
        *self
    }
}
pub type STGC = i32;
pub type STGM = u32;
#[repr(C)]
pub struct STGMEDIUM {
    pub tymed: TYMED,
    pub u: STGMEDIUM_0,
    pub pUnkForRelease: IUnknown,
}
impl ::core::marker::Copy for STGMEDIUM {}
impl ::core::clone::Clone for STGMEDIUM {
    fn clone(&self) -> Self {
        *self
    }
}
#[repr(C)]
pub union STGMEDIUM_0 {
    pub hBitmap: HBITMAP,
    pub hMetaFilePict: *mut ::core::ffi::c_void,
    pub hEnhMetaFile: HENHMETAFILE,
    pub hGlobal: HGLOBAL,
    pub lpszFileName: PWSTR,
    pub pstm: IStream,
    pub pstg: IStorage,
}
impl ::core::marker::Copy for STGMEDIUM_0 {}
impl ::core::clone::Clone for STGMEDIUM_0 {
    fn clone(&self) -> Self {
        *self
    }
}
pub type STGMOVE = i32;
pub type STREAM_SEEK = u32;
pub type SYSTEM_PARAMETERS_INFO_ACTION = u32;
pub type SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS = u32;
pub const S_OK: HRESULT = 0i32;
pub type TYMED = i32;
pub const TYMED_HGLOBAL: TYMED = 1i32;
pub const WAIT_TIMEOUT: WIN32_ERROR = 258u32;
pub type WIN32_ERROR = u32;
