output = "bindings.rs"
binds = [
    # Foundation
    "S_OK",
    "NTSTATUS",
    "POINT",
    "POINTS",
    "WAIT_TIMEOUT",
    # COM
    "CoCreateInstance",
    "CLSCTX_ALL",
    "CoInitializeEx",
    "COINIT_APARTMENTTHREADED",
    "CoUninitialize",
    # Ole
    "OLE_E_WRONGCOMPOBJ",
    "RPC_E_CHANGED_MODE",
    "OleInitialize",
    "RegisterDragDrop",
    # Drag'n'Drop
    "DragQueryFileW",
    "DragFinish",
    "RevokeDragDrop",
    "CF_HDROP",
    "DROPEFFECT_COPY",
    "DROPEFFECT_NONE",
    "DV_E_FORMATETC",
    "DVASPECT_CONTENT",
    "FORMATETC",
    "HDROP",
    "IDataObject",
    "STGMEDIUM",
    "TYMED_HGLOBAL",
    # Dark mode
    "LoadLibraryA",
    "GetProcAddress",
    "SetWindowTheme",
    "SystemParametersInfoA",
    "HCF_HIGHCONTRASTON",
    "HIGHCONTRASTA",
    "OSVERSIONINFOW",
    "SPI_GETHIGHCONTRAST",
    # Gdi/Graphics
    "ChangeDisplaySettingsExW",
    "ClientToScreen",
    "CreateRectRgn",
    "DeleteObject",
    "DwmEnableBlurBehindWindow",
    "EnumDisplayMonitors",
    "EnumDisplaySettingsExW",
    "GetDC",
    "GetDeviceCaps",
    "GetMonitorInfoW",
    "InvalidateRgn",
    "LoadImageW",
    "MonitorFromPoint",
    "MonitorFromRect",
    "MonitorFromWindow",
    "RedrawWindow",
    "ScreenToClient",
    "ValidateRect",
    "CDS_FULLSCREEN",
    "DISP_CHANGE_BADFLAGS",
    "DISP_CHANGE_BADMODE",
    "DISP_CHANGE_BADPARAM",
    "DISP_CHANGE_FAILED",
    "DISP_CHANGE_SUCCESSFUL",
    "DM_BITSPERPEL",
    "DM_DISPLAYFREQUENCY",
    "DM_PELSHEIGHT",
    "DM_PELSWIDTH",
    "DWM_BB_BLURREGION",
    "DWM_BB_ENABLE",
    "DWM_BLURBEHIND",
    "ENUM_CURRENT_SETTINGS",
    "LOGPIXELSX",
    "MONITOR_DEFAULTTONEAREST",
    "MONITOR_DEFAULTTONULL",
    "MONITOR_DEFAULTTOPRIMARY",
    "MONITORINFOEXW",
    "RDW_INTERNALPAINT",
    "SC_MINIMIZE",
    "SC_RESTORE",
    "SC_SCREENSAVE",
    # DPI
    "IsProcessDPIAware",
    "DPI_AWARENESS_CONTEXT",
    "DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE",
    "MDT_EFFECTIVE_DPI",
    "PROCESS_PER_MONITOR_DPI_AWARE",
    # Windows/Message Pump
    "AdjustWindowRectEx",
    "ClipCursor",
    "CreateIcon",
    "CreateWindowExW",
    "DispatchMessageW",
    "DefWindowProcW",
    "DestroyIcon",
    "DestroyWindow",
    "EnableMenuItem",
    "FlashWindowEx",
    "GetClientRect",
    "GetClipCursor",
    "GetCursorPos",
    "GetMenu",
    "GetForegroundWindow",
    "GetMessageW",
    "GetSystemMenu",
    "GetSystemMetrics",
    "GetUpdateRect",
    "GetWindowLongW",
    "GetWindowLongPtrW",
    "GetWindowPlacement",
    "GetWindowRect",
    "GetWindowTextLengthW",
    "GetWindowTextW",
    "IsIconic",
    "IsWindowVisible",
    "LoadCursorW",
    "MsgWaitForMultipleObjectsEx",
    "PeekMessageW",
    "PostMessageW",
    "PostThreadMessageW",
    "RegisterClassExW",
    "RegisterWindowMessageA",
    "SendMessageW",
    "SetCursor",
    "SetCursorPos",
    "SetForegroundWindow",
    "SetWindowDisplayAffinity",
    "SetWindowLongW",
    "SetWindowLongPtrW",
    "SetWindowPlacement",
    "SetWindowPos",
    "SetWindowTextW",
    "ShowCursor",
    "ShowWindow",
    "TranslateMessage",
    "CREATESTRUCTW",
    "CS_HREDRAW",
    "CS_VREDRAW",
    "CW_USEDEFAULT",
    "DEVMODEW+Clone",
    "FLASHWINFO",
    "FLASHW_ALL",
    "FLASHW_STOP",
    "FLASHW_TIMERNOFG",
    "FLASHW_TRAY",
    "GIDC_ARRIVAL",
    "GIDC_REMOVAL",
    "GWL_EXSTYLE",
    "GWL_USERDATA",
    "GWL_STYLE",
    "GWLP_HINSTANCE",
    "HTCAPTION",
    "HTCLIENT",
    "HWND_BOTTOM",
    "HWND_NOTOPMOST",
    "HWND_TOPMOST",
    "ICON_BIG",
    "ICON_SMALL",
    "IDC_APPSTARTING",
    "IDC_ARROW",
    "IDC_CROSS",
    "IDC_HAND",
    "IDC_HELP",
    "IDC_IBEAM",
    "IDC_NO",
    "IDC_SIZEALL",
    "IDC_SIZENESW",
    "IDC_SIZENS",
    "IDC_SIZENWSE",
    "IDC_SIZEWE",
    "IDC_WAIT",
    "IMAGE_ICON",
    "LR_DEFAULTSIZE",
    "LR_LOADFROMFILE",
    "MF_BYCOMMAND",
    "MF_DISABLED",
    "MF_ENABLED",
    "MINMAXINFO",
    "MNC_CLOSE",
    "MOUSE_MOVE_RELATIVE",
    "MSG",
    "MWMO_INPUTAVAILABLE",
    "NCCALCSIZE_PARAMS",
    "NID_READY",
    "PM_NOREMOVE",
    "PM_QS_PAINT",
    "PM_REMOVE",
    "PT_PEN",
    "PT_TOUCH",
    "QS_ALLEVENTS",
    "RI_MOUSE_WHEEL",
    "SC_CLOSE",
    "SIZE_MAXIMIZED",
    "SM_CXVIRTUALSCREEN",
    "SM_CYVIRTUALSCREEN",
    "SM_DIGITIZER",
    "SM_XVIRTUALSCREEN",
    "SM_YVIRTUALSCREEN",
    "SWP_ASYNCWINDOWPOS",
    "SWP_FRAMECHANGED",
    "SWP_NOACTIVATE",
    "SWP_NOMOVE",
    "SWP_NOREPOSITION",
    "SWP_NOSIZE",
    "SWP_NOZORDER",
    "SW_HIDE",
    "SW_MAXIMIZE",
    "SW_MINIMIZE",
    "SW_RESTORE",
    "SW_SHOW",
    "SW_SHOWNOACTIVATE",
    "WDA_EXCLUDEFROMCAPTURE",
    "WDA_NONE",
    "WHEEL_DELTA",
    "WINDOWPLACEMENT+Clone",
    "WINDOWPOS",
    "WM_CAPTURECHANGED",
    "WM_CHAR",
    "WM_CLOSE",
    "WM_CREATE",
    "WM_DESTROY",
    "WM_DPICHANGED",
    "WM_DROPFILES",
    "WM_ENTERSIZEMOVE",
    "WM_EXITSIZEMOVE",
    "WM_GETMINMAXINFO",
    "WM_IME_COMPOSITION",
    "WM_IME_ENDCOMPOSITION",
    "WM_IME_SETCONTEXT",
    "WM_IME_STARTCOMPOSITION",
    "WM_INPUT",
    "WM_INPUT_DEVICE_CHANGE",
    "WM_KEYDOWN",
    "WM_KEYUP",
    "WM_KILLFOCUS",
    "WM_LBUTTONDOWN",
    "WM_LBUTTONUP",
    "WM_MBUTTONDOWN",
    "WM_MBUTTONUP",
    "WM_MENUCHAR",
    "WM_MOUSEHWHEEL",
    "WM_MOUSELEAVE",
    "WM_MOUSEMOVE",
    "WM_MOUSEWHEEL",
    "WM_NCACTIVATE",
    "WM_NCCALCSIZE",
    "WM_NCCREATE",
    "WM_NCDESTROY",
    "WM_NCLBUTTONDOWN",
    "WM_PAINT",
    "WM_POINTERDOWN",
    "WM_POINTERUP",
    "WM_POINTERUPDATE",
    "WM_RBUTTONDOWN",
    "WM_RBUTTONUP",
    "WM_SETCURSOR",
    "WM_SETFOCUS",
    "WM_SETICON",
    "WM_SETTINGCHANGE",
    "WM_SIZE",
    "WM_SYSCHAR",
    "WM_SYSCOMMAND",
    "WM_SYSKEYDOWN",
    "WM_SYSKEYUP",
    "WM_TOUCH",
    "WM_WINDOWPOSCHANGED",
    "WM_WINDOWPOSCHANGING",
    "WM_XBUTTONDOWN",
    "WM_XBUTTONUP",
    "WNDCLASSEXW",
    "WS_BORDER",
    "WS_CAPTION",
    "WS_CHILD",
    "WS_CLIPCHILDREN",
    "WS_CLIPSIBLINGS",
    "WS_EX_ACCEPTFILES",
    "WS_EX_APPWINDOW",
    "WS_EX_LAYERED",
    "WS_EX_NOACTIVATE",
    "WS_EX_NOREDIRECTIONBITMAP",
    "WS_EX_TOOLWINDOW",
    "WS_EX_TOPMOST",
    "WS_EX_TRANSPARENT",
    "WS_EX_WINDOWEDGE",
    "WS_MAXIMIZE",
    "WS_MAXIMIZEBOX",
    "WS_MINIMIZE",
    "WS_MINIMIZEBOX",
    "WS_OVERLAPPED",
    "WS_OVERLAPPEDWINDOW",
    "WS_POPUP",
    "WS_SIZEBOX",
    "WS_SYSMENU",
    "WS_VISIBLE",
    "WNDCLASSEXW",
    # Input
    "CloseTouchInputHandle",
    "EnableWindow",
    "GetActiveWindow",
    "GetKeyState",
    "GetKeyboardLayout",
    "GetKeyboardState",
    "GetTouchInputInfo",
    "MapVirtualKeyA",
    "MapVirtualKeyW",
    "RegisterTouchWindow",
    "ReleaseCapture",
    "SendInput",
    "SetCapture",
    "ToUnicodeEx",
    "TrackMouseEvent",
    "GCS_COMPSTR",
    "GCS_RESULTSTR",
    "INPUT",
    "INPUT_KEYBOARD",
    "ISC_SHOWUICOMPOSITIONWINDOW",
    "KEYBDINPUT",
    "KEYEVENTF_EXTENDEDKEY",
    "KEYEVENTF_KEYUP",
    "MAPVK_VK_TO_CHAR",
    "MAPVK_VK_TO_VSC",
    "MAPVK_VSC_TO_VK_EX",
    "POINTER_FLAG_DOWN",
    "POINTER_FLAG_UP",
    "POINTER_FLAG_UPDATE",
    "POINTER_INFO",
    "POINTER_PEN_INFO",
    "POINTER_TOUCH_INFO",
    "RI_KEY_E0",
    "RI_KEY_E1",
    "RIM_TYPEKEYBOARD",
    "RIM_TYPEMOUSE",
    "VK_LMENU",
    "VK_MENU",
    "TME_LEAVE",
    "TOUCHEVENTF_DOWN",
    "TOUCHEVENTF_MOVE",
    "TOUCHEVENTF_UP",
    "TOUCHINPUT",
    "TRACKMOUSEEVENT",
    "TWF_WANTPALM",
    "VK_0",
    "VK_1",
    "VK_2",
    "VK_3",
    "VK_4",
    "VK_5",
    "VK_6",
    "VK_7",
    "VK_8",
    "VK_9",
    "VK_A",
    "VK_ADD",
    "VK_APPS",
    "VK_B",
    "VK_BACK",
    "VK_BROWSER_BACK",
    "VK_BROWSER_FAVORITES",
    "VK_BROWSER_FORWARD",
    "VK_BROWSER_HOME",
    "VK_BROWSER_REFRESH",
    "VK_BROWSER_SEARCH",
    "VK_BROWSER_STOP",
    "VK_C",
    "VK_CAPITAL",
    "VK_CONTROL",
    "VK_CONVERT",
    "VK_D",
    "VK_DECIMAL",
    "VK_DELETE",
    "VK_DIVIDE",
    "VK_DOWN",
    "VK_E",
    "VK_END",
    "VK_ESCAPE",
    # We need to force use constant here, otherwise we get a struct named
    # VK_F since it's in the same namespace :(
    "constant-VK_F",
    "VK_F1",
    "VK_F10",
    "VK_F11",
    "VK_F12",
    "VK_F13",
    "VK_F14",
    "VK_F15",
    "VK_F16",
    "VK_F17",
    "VK_F18",
    "VK_F19",
    "VK_F2",
    "VK_F20",
    "VK_F21",
    "VK_F22",
    "VK_F23",
    "VK_F24",
    "VK_F3",
    "VK_F4",
    "VK_F5",
    "VK_F6",
    "VK_F7",
    "VK_F8",
    "VK_F9",
    "VK_G",
    "VK_H",
    "VK_HOME",
    "VK_I",
    "VK_INSERT",
    "VK_J",
    "VK_K",
    "VK_KANA",
    "VK_KANJI",
    "VK_L",
    "VK_LAUNCH_MAIL",
    "VK_LAUNCH_MEDIA_SELECT",
    "VK_LCONTROL",
    "VK_LEFT",
    "VK_LMENU",
    "VK_LSHIFT",
    "VK_LWIN",
    "VK_M",
    "VK_MEDIA_NEXT_TRACK",
    "VK_MEDIA_PLAY_PAUSE",
    "VK_MEDIA_PREV_TRACK",
    "VK_MEDIA_STOP",
    "VK_MENU",
    "VK_MULTIPLY",
    "VK_N",
    "VK_NEXT",
    "VK_NONCONVERT",
    "VK_NUMLOCK",
    "VK_NUMPAD0",
    "VK_NUMPAD1",
    "VK_NUMPAD2",
    "VK_NUMPAD3",
    "VK_NUMPAD4",
    "VK_NUMPAD5",
    "VK_NUMPAD6",
    "VK_NUMPAD7",
    "VK_NUMPAD8",
    "VK_NUMPAD9",
    "VK_O",
    "VK_OEM_1",
    "VK_OEM_102",
    "VK_OEM_2",
    "VK_OEM_3",
    "VK_OEM_4",
    "VK_OEM_5",
    "VK_OEM_6",
    "VK_OEM_7",
    "VK_OEM_COMMA",
    "VK_OEM_MINUS",
    "VK_OEM_PERIOD",
    "VK_OEM_PLUS",
    "VK_P",
    "VK_PAUSE",
    "VK_PRIOR",
    "VK_Q",
    "VK_R",
    "VK_RCONTROL",
    "VK_RETURN",
    "VK_RIGHT",
    "VK_RMENU",
    "VK_RSHIFT",
    "VK_RWIN",
    "VK_S",
    "VK_SCROLL",
    "VK_SHIFT",
    "VK_SLEEP",
    "VK_SNAPSHOT",
    "VK_SPACE",
    "VK_SUBTRACT",
    "VK_T",
    "VK_TAB",
    "VK_U",
    "VK_UP",
    "VK_V",
    "VK_VOLUME_DOWN",
    "VK_VOLUME_MUTE",
    "VK_VOLUME_UP",
    "VK_W",
    "VK_X",
    "VK_Y",
    "VK_Z",
    # Raw input
    "GetRawInputData",
    "GetRawInputDeviceInfoW",
    "GetRawInputDeviceList",
    "RegisterRawInputDevices",
    "HID_USAGE_GENERIC_KEYBOARD",
    "HID_USAGE_GENERIC_MOUSE",
    "HID_USAGE_PAGE_GENERIC",
    "RAWINPUT",
    "RAWINPUTDEVICE",
    "RAWINPUTDEVICELIST",
    "RI_MOUSE_LEFT_BUTTON_DOWN",
    "RI_MOUSE_LEFT_BUTTON_UP",
    "RI_MOUSE_MIDDLE_BUTTON_DOWN",
    "RI_MOUSE_MIDDLE_BUTTON_UP",
    "RI_MOUSE_RIGHT_BUTTON_DOWN",
    "RI_MOUSE_RIGHT_BUTTON_UP",
    "RID_DEVICE_INFO",
    "RID_DEVICE_INFO_HID",
    "RID_DEVICE_INFO_KEYBOARD",
    "RID_DEVICE_INFO_MOUSE",
    "RIDEV_DEVNOTIFY",
    "RIDEV_INPUTSINK",
    "RIDEV_REMOVE",
    "RIDI_DEVICEINFO",
    "RIDI_DEVICENAME",
    "RID_INPUT",
    "RIM_TYPEHID",
    # Ime
    "ImmAssociateContextEx",
    "ImmGetCompositionStringW",
    "ImmGetContext",
    "ImmReleaseContext",
    "ImmSetCandidateWindow",
    "ATTR_TARGET_CONVERTED",
    "ATTR_TARGET_NOTCONVERTED",
    "CFS_EXCLUDE",
    "GCS_COMPATTR",
    "GCS_COMPSTR",
    "GCS_CURSORPOS",
    "GCS_RESULTSTR",
    "IACE_CHILDREN",
    "IACE_DEFAULT",
    "SM_IMMENABLED",
    # Miscellaneous
    "GetCurrentThreadId",
    "timeBeginPeriod",
    "timeEndPeriod",
    "timeGetDevCaps",
    "HOVER_DEFAULT",
    "IMAGE_DOS_HEADER",
    "INFINITE",
    "TIMECAPS",
    "TIMERR_NOERROR",
]
